### ISSUE TITLE
gradle build in demo_gradle is broken

### ISSUE THREAD

**Issue by vimalanandans** [decebals/pf4j#100]
gradle clean build
:api:clean UP-TO-DATE
:app:clean UP-TO-DATE
:plugins/plugin1:clean UP-TO-DATE
:plugins/plugin2:clean UP-TO-DATE
:api:compileJava
NEGOTIATE authentication error: No valid credentials provided (Mechanism level:                                                                               No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)                                                                              )
C:\Work\03_PAB\git\sandbox\pf4j\demo_gradle\api\src\main\java\ro\fortsoft\pf4j\d                                                                              emo\api\Greeting.java:16: error: class, interface, or enum expected
 */
 ^
1 error
:api:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':api:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                               option to get more log output.

BUILD FAILED

Total time: 48.204 secs
Picked up _JAVA_OPTIONS: -Xmx1g

**Comment by decebals** [comment]
I don't use gradle in my projects so I don't know how can I fix your error :(
Maybe someone (@stiXits ) can help us.

**Comment by vimalanandans** [comment]
ok thanks! i will try my search around.

**Comment by vimalanandans** [comment]
greetingj.java has additional */ in the header. removing that builds fine

**Comment by decebals** [comment]
I made the modification. Please try again and confirm that the modification resolves the issue. Thanks.

**Comment by vimalanandans** [comment]
It is building. Thanks for the quick response.
