### ISSUE TITLE
PluginDescriptor can't be extended

### ISSUE THREAD

**Issue by DimaSol** [decebals/pf4j#107]
Hi,
I'm not sure if this is in purpose but there is no way to extend the PluginDescriptor to support custom properties.
I'm extending ManifestPluginDescriptorFinder to create a CustomPluginDescriptor but createPluginDescriptor is the one that is creating the PluginDescriptor so I have to fully override the createPluginDescriptor and call all the core properties setters but the setters are private to the package so it becames very not pretty...
I would expect the PluginDescriptorFinder interface or ManifestPluginDescriptorFinder class to have a public PluginDescriptor createDescriptorInstance method that will return a new instance (and this one can be simply overriden by any PluginDescriptorFinder inplementation), in such way in the extending createPluginDescriptor method a super.createPluginDescriptor can be called to init all core properties and getting back the extending custom PluginDescriptor that can be further enhanced.

**Comment by decebals** [comment]
> I'm not sure if this is in purpose but there is no way to extend the PluginDescriptor to support custom properties.

I don't understand why (and where) you need custom properties.

 > I'm extending ManifestPluginDescriptorFinder to create a CustomPluginDescriptor but createPluginDescriptor is the one that is creating the PluginDescriptor so I have to fully override the createPluginDescriptor and call all the core properties setters but the setters are private to the package so it becames very not pretty...
I would expect the PluginDescriptorFinder interface or ManifestPluginDescriptorFinder class to have a public PluginDescriptor createDescriptorInstance method that will return a new instance (and this one can be simply overriden by any PluginDescriptorFinder inplementation), in such way in the extending createPluginDescriptor method a super.createPluginDescriptor can be called to init all core properties and getting back the extending custom PluginDescriptor that can be further enhanced.

I can extract the `PluginDescriptor pluginDescriptor = new PluginDescriptor();` line from the `ManifestPluginDescriptorFinder.createPluginDescriptor(Manifest manifest)` method in a protected method `createPluginDescriptorInstance` and you can use the variant with `super.createPluginDescriptor`.
Until this issue I didn't found a reason why someone needs to create a custom PluginDescriptor instance but maybe you can give me a good reason to do this.

**Comment by DimaSol** [comment]
Thank you for the reply.

You are giving the ability to configure my PluginDescriptorFinder by providing a protected createPluginDescriptorFinder method and one of the things I want my descriptor finder to do is to parse extra custom attributes - I think it will only by consistent to support also an extension of the PluginDescriptor.

An example for such need is: my plugins are holding extensions for JSF application and I need the ability to define in the manifest the components that are being added to specific panels, JSF managed beans and maybe hinerante domain objects.

**Comment by decebals** [comment]
I made the modification and you can do your job but to be honest with you I don't understand why you want to use `PluginDescriptor` for a such task. You can move all this logic with read the Manifest and extract some metadata in a `AcmePlugin` (your base plugin class) that extends Plugin class.

**Comment by DimaSol** [comment]
You are right and this is how I've implemented it up until now, but such an implementation leads to parsing the manifest again what I think is not pretty - If we already have a utility that is doing it, I would like to use it instead of re-inventing it again...
Anyway, thank you for modifienf it.

**Comment by decebals** [comment]
Can you close this issue, of course if everything is OK for you?

**Comment by DimaSol** [comment]
Sure, when this fix planned to be released?

**Comment by decebals** [comment]
> Sure, when this fix planned to be released?

I wait a feedback for https://github.com/decebals/pf4j/pull/108 and if everything is OK a can release a next version.

**Comment by DimaSol** [comment]
Hi,
Can you kindly share an estimation when is the next version going to be released?

**Comment by decebals** [comment]
Probably tonight or tomorrow morning.

**Comment by decebals** [comment]
Done
