### ISSUE TITLE
Extension Annotation Processing Support for Kotlin Classes

### ISSUE THREAD

**Issue by shaigem** [decebals/pf4j#109]
Will there be any support for generating the extensions.idx file for all Kotlin classes that are marked with the Extensions annotation?

**Comment by decebals** [comment]
Interesting use case. I know nothing about Kotlin but I will try to take a look. Can you help me somehow to  add support for Kotlin?

**Comment by anidotnet** [comment]
Any progress on this? I am also looking for Kotlin support.

**Comment by decebals** [comment]
@anidotnet 
I explained in my previous comment that I know nothing (yet) about Kotlin. In this context I am not aware about the nature of PF4J problems in Kotlin. Why it is not possible to generate extensions.idx in Kotlin. I know that Kotlin is a JVM language (as Scala for example). Is it not possible to use Annotation Processors in Kotlin application?

**Comment by decebals** [comment]
From PF4J readme
> `DefaultExtensionFinder` looks up extensions using `Extension` annotation.
`DefaultExtensionFinder` looks up extensions in all extensions index files `META-INF/extensions.idx`. PF4J uses Java Annotation Processing to process at compile time all classes annotated with `@Extension` and to produce the extensions index file.

I found something about Annotation Processing in Kotlin from [this article](
https://medium.com/@workingkills/pushing-the-limits-of-kotlin-annotation-processing-8611027b6711).

**Comment by anidotnet** [comment]
So it looks like we have hit a roadblock!

**Comment by anidotnet** [comment]
The only other way I can see is to fork this project and use reflection instead of annotation processing.

**Comment by decebals** [comment]
@anidotnet 
> The only other way I can see is to fork this project and use reflection instead of annotation processing.

It's much simple. PF4J allows you to customize many aspects. 
For example, a clean solution to your problem is to create a new class that implements [ExtensionFinder](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/ro/fortsoft/pf4j/ExtensionFinder.java) interface from scratch or to extend [AbstractExtensionFinder](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/ro/fortsoft/pf4j/AbstractExtensionFinder.java). No need for fork the project.

**Comment by anidotnet** [comment]
I'll have a look at it and let you know if I face any issue.

**Comment by anidotnet** [comment]
I have made it work using reflection. But for this I had to add below dependency

```xml
<dependency>
    <groupId>org.reflections</groupId>
    <artifactId>reflections</artifactId>
    <version>0.9.11</version>
</dependency>
```

And here is the custom plugin manager and extension finder.

```java
package me.practice.pf4j;

import ro.fortsoft.pf4j.DefaultPluginManager;
import ro.fortsoft.pf4j.ExtensionFinder;

/**
 * @author Anindya Chatterjee
 */
public class ReflectivePluginManager extends DefaultPluginManager {

    @Override
    protected ExtensionFinder createExtensionFinder() {
        ReflectiveExtensionFinder extensionFinder = new ReflectiveExtensionFinder(this);
        addPluginStateListener(extensionFinder);
        return extensionFinder;
    }
}
```
and

```java
package me.practice.pf4j;

import org.reflections.Reflections;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ro.fortsoft.pf4j.AbstractExtensionFinder;
import ro.fortsoft.pf4j.Extension;
import ro.fortsoft.pf4j.PluginManager;
import ro.fortsoft.pf4j.PluginWrapper;

import java.util.*;

/**
 * @author Anindya Chatterjee
 */
public class ReflectiveExtensionFinder extends AbstractExtensionFinder {
    private static final Logger log = LoggerFactory.getLogger(ReflectiveExtensionFinder.class);
    private List<String> packageList;

    ReflectiveExtensionFinder(PluginManager pluginManager, String... packages) {
        super(pluginManager);
        this.packageList = new ArrayList<>();
        this.packageList.addAll(Arrays.asList(packages));
    }

    @Override
    public Map<String, Set<String>> readPluginsStorages() {
        log.debug("Reading extensions storages from plugins");
        Map<String, Set<String>> result = new LinkedHashMap<>();

        List<PluginWrapper> plugins = pluginManager.getPlugins();
        for (PluginWrapper plugin : plugins) {
            String pluginId = plugin.getDescriptor().getPluginId();
            log.debug("Reading extensions storage from plugin '{}'", pluginId);
            Set<String> bucket = new HashSet<>();

            ClassLoader classLoader = plugin.getPluginClassLoader();
            Reflections reflections = new Reflections(classLoader);
            Set<Class<?>> classes = reflections.getTypesAnnotatedWith(Extension.class);
            for (Class<?> clazz : classes) {
                bucket.add(clazz.getName());
            }

            debugExtensions(bucket);
            result.put(pluginId, bucket);
        }

        return result;
    }

    @Override
    public Map<String, Set<String>> readClasspathStorages() {
        log.debug("Reading extensions storages from classpath");
        Map<String, Set<String>> result = new LinkedHashMap<>();
        Set<String> bucket = new HashSet<>();

        for (String pkg: packageList) {
            Reflections reflections = new Reflections(pkg);
            Set<Class<?>> classes = reflections.getTypesAnnotatedWith(Extension.class);
            for (Class<?> clazz : classes) {
                bucket.add(clazz.getName());
            }
        }

        debugExtensions(bucket);
        result.put(null, bucket);

        return result;
    }
}
```
Let me know if you want a pull request for it or not.

**Comment by decebals** [comment]
@anidotnet 
Good job. Now you see that it's easy to modify some default behaviors of PF4J.
I try to use PF4J with minimal dependencies. Reflections comes with new dependencies like Guava. It's too much for a functionality that  it's used occasionally.
I accept a PR if you can remove the reflections library as dependency. I don't know how easy is to create a method `getTypesAnnotatedWith` in ReflectiveExtensionFinder class only using Java core.

**Comment by anidotnet** [comment]
I am thinking to create a new module for kotlin itself, where I'll put these logic in kotlin and in future if anyone wants to leverage any kotlin specific functionality he/she can do that in that module. In that case your main pf4j module will remain clean and will not be burned with third-party libraries like these. Let me know your thoughts.

**Comment by anidotnet** [comment]
It turns out that I don't have to write a new module or anything. One has to use **kotlin-kapt** plugin to do the annotation processing and add this line **kapt 'ro.fortsoft.pf4j:pf4j:1.3.0'** in the dependencies.

Here is the example ```build.gradle``` for a plugin project written in kotlin

```gradle
buildscript {
    ext.kotlin_version = '1.1.2-2'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

jar {
    baseName = 'WelcomePlugin'
    version = '0.1.0'
    manifest {
        attributes 'Plugin-Class' : 'me.practice.plugin.WelcomePlugin',
                'Plugin-Id' : 'WelcomePlugin',
                'Plugin-Version' : '1.0.0',
                'Plugin-Provider' : 'Decebal Suiu'
    }
}

task plugin(type: Jar) {
    baseName = 'WelcomePlugin'
    version = '0.1.0'
    into('classes'){
        with jar
    }
    into('lib'){
        from configurations.compile
    }
    extension('zip')
}
assemble.dependsOn plugin

group 'me.practice'

apply plugin: 'kotlin'
apply plugin: 'kotlin-kapt'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly project(':demo-api') // compileOnly important!!! We do not want to put the api into the zip file since the main program has it already!
    kapt 'ro.fortsoft.pf4j:pf4j:1.3.0'
    compile 'org.apache.commons:commons-lang3:3.0'
    testCompile group: 'junit', name: 'junit', version: '4.+'
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$kotlin_version"
}
```
Same configuration needs to be done if the app module also contains a plugin. It turns out to be a very simple solution out of the box. The dagger2 kotlin example gave me the idea. Could you please add this in your project manual?

**Comment by decebals** [comment]
It's very good news. If you have few minutes, please add a new section `Kotlin` in README.md with information from your previous. Thanks!

**Comment by anidotnet** [comment]
I have added the PR with a demo plugin written in kotlin

**Comment by turovaia** [comment]
@anidotnet, It seems that kotlin implementation of greeting interface itn't found by plugin. It prints that only 3 implementations were found and "KotlinGreetings" wasn't printed
