### ISSUE TITLE
Unexpected character 'EOI(null)' at position '1', expecting '[DOT]'

### ISSUE THREAD

**Issue by TempUsername000** [decebals/pf4j#114]
> [12:52:22] [INFO] DefaultPluginManager:774 - PF4J version 1.1.0 in 'deployment' mode 
> [12:52:22] [INFO] DefaultPluginStatusProvider:50 - Enabled plugins: [] 
> [12:52:22] [INFO] DefaultPluginStatusProvider:54 - Disabled plugins: [] 
> [12:52:22] [DEBUG] DefaultPluginManager:367 - Lookup plugins in '/home/bot/.test/plugins' 
> [12:52:22] [DEBUG] DefaultPluginManager:391 - Found 1 possible plugins: [/home/bot/.test/plugins/TestPlugin-1.0] 
> [12:52:22] [DEBUG] DefaultPluginManager:803 - Find plugin descriptor '/TestPlugin-1.0' 
> [12:52:22] [DEBUG] ManifestPluginDescriptorFinder:59 - Lookup plugin descriptor in '/home/bot/.test/plugins/TestPlugin-1.0/classes/META-INF/MANIFEST.MF' 
> Exception in thread "AWT-EventQueue-0" Unexpected character 'EOI(null)' at position '1', expecting '[DOT]'
> 	at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
> 	at com.github.zafarkhaja.semver.VersionParser.parseVersionCore(VersionParser.java:286)
> 	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:255)
> 	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
> 	at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)
> 	at ro.fortsoft.pf4j.ManifestPluginDescriptorFinder.createPluginDescriptor(ManifestPluginDescriptorFinder.java:107)
> 	at ro.fortsoft.pf4j.ManifestPluginDescriptorFinder.find(ManifestPluginDescriptorFinder.java:49)
> 	at ro.fortsoft.pf4j.DefaultPluginManager.loadPluginDirectory(DefaultPluginManager.java:804)
> 	at ro.fortsoft.pf4j.DefaultPluginManager.loadPlugins(DefaultPluginManager.java:400)
> 	at me.tempuser.testapi.model.PluginModel.getInstance(PluginModel.java:29)
> 	at me.tempuser.testapi.model.ParseModel.getSupportedExtensions(ParseModel.java:26)
> 	at me.tempuser.test.Test.lambda$main$0(test.java:41)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Plugin tree:
> .
  └── classes
  ├── me
    │   └── tempuser
    │       └── test
    │           └── plugins
    │               ├── TestPlugin.class
    │               └── TestPlugin$TestPlugin.class
    └── META-INF
        ├── extensions.idx
        ├── MANIFEST.MF
        └── maven
            └── me.tempuser.test.plugins
                └── TestPlugin
                    ├── pom.properties
                    └── pom.xml

MANIFEST.MF:
> Manifest-Version: 1.0
> Plugin-Id: TestPlugin
> Archiver-Version: Plexus Archiver
> Built-By: bot
> Plugin-Provider: TempUser
> Plugin-Version: 1.0
> Plugin-Class: me.tempuser.test.plugins.TestPlugin
> Created-By: Apache Maven 3.3.9
> Build-Jdk: 1.8.0_102

(With a newline at the end)

What am I doing wrong?
If you need any other information let me know

**Comment by TempUsername000** [comment]
Of course just as I post this I realize the problem:
The "Plugin-Version: 1.0" should be 

> major.minor.patch

"Plugin-Version: 0.0.1" works fine.

**Comment by decebals** [comment]
The plugin version must be compliant with Semantic Versioning [1]. Now PF4J uses `jsemver` because it comes with support for comparing versions. In the past was a simple class `Version`. It's a comment in an old issue that comes with details but for the moment I don't find that comment.
Maybe it's time to improve documentation (README.md) related to this subject.

[1] http://semver.org
[2] https://github.com/zafarkhaja/jsemver

**Comment by decebals** [comment]
See https://github.com/decebals/pf4j/pull/44
