### ISSUE TITLE
Binding Errors, Gradle Development Support

### ISSUE THREAD

**Issue by mcjp78** [decebals/pf4j#117]
So i've found a few issues. When using Sl4j simple in plugin  A, and using Logback in the main project it will throw errors due to different bindings. Upon looking at pf4j code, I believe this is a class resolution conflict, therefore I believe it would be beneficial if the parent class loader was checked prior to the plugin's libs (As opposed to the child first method). 

Second issue is that the development mode only supports maven. I've resolved this in my project and will open a PR soon.

**Comment by decebals** [comment]
> So i've found a few issues. When using Sl4j simple in plugin A, and using Logback in the main project it will throw errors due to different bindings. Upon looking at pf4j code, I believe this is a class resolution conflict, therefore I believe it would be beneficial if the parent class loader was checked prior to the plugin's libs (As opposed to the child first method).

I can create a flag (childFirst or parentFirst), preserve the current behavior (childFirst) but give you the possibility to set parentFirst option. Make sense for you?

> Second issue is that the development mode only supports maven. I've resolved this in my project and will open a PR soon.

I don't use Gradle, so all Gradle support is contributed by other people. You are welcome with any contribution.

**Comment by mcjp78** [comment]
Yep! Flag would be awesome . Okay, will add some contributions

**Comment by janhoy** [comment]
Plugins should in my opinion not bundle an slf4j binding at all, but default that to whatever the main app chooses to use. What do you think @mcjp78 ?

**Comment by mcjp78** [comment]
This issue is from quite a while ago, never did open that pr did I. Janhoy it should default to what the parent wants, that's why it's parent first

**Comment by janhoy** [comment]
Yep, but if the plugin does not contain `slf4j-simple-x.y.jar` then the class loader will look in parent (last) and find the logger binding. You are never supposed to have multiple bindings present in a single application, as slf4j will pick the first one it finds.

**Comment by mcjp78** [comment]
sorry uh that's what we said the entire time ? It needs to pick THE PARENT first so it needs be parent first ?? He said he would add a flag to do that ?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by decebals** [comment]
I think that I can add this feature with few code. This option is available in many application servers.
No it's possible to use any ClassLoader you wish. So, if you change PluginClassLoader with a custom ClassLoader that support child/parent first option everything is perfect. A good (but a little bit complicated) custom ClassLoader is [JCL](https://github.com/kamranzafar/JCL).

**Comment by decebals** [comment]
Resolved by 0438f0ac258e37cec6dd9cd4720ac38942d45595.
