### ISSUE TITLE
Can't find extensions when api uses a different package name then "ro.fortsoft.pf4j.demo.api"

### ISSUE THREAD

**Issue by lyze237** [decebals/pf4j#123]
Hello!

I've checked out the demo_gradle project of the code base and tried to add a couple extensions.

Whenever I add a new ExtensionPoint, lets say "com.thyllian.Hallo" with the following content:

    package ro.fortsoft.pf4j.demo.api;

    import ro.fortsoft.pf4j.ExtensionPoint;

    public interface Hallo extends ExtensionPoint {
        public String getHallo();
    }

And add the newly created ExtensionPoint to "plugin1/WelcomeGreeting":

    @Extension
    public static class WelcomeGreeting implements Greeting, Hallo {
    	@Override
        public String getGreeting() {
            return "Welcome";
        }
        @Override
        public String getHallo() {
            return "Hallo";
        }
    }

Pf4j can't find WelcomeGreeting when executing pluginManager.getExtensions(Hallo.class);

Now however when I move the "at.lyze.api.Hallo" class to "ro.fortsoft.pf4j.demo.api.Hallo" and fix all imports it it works.

Log files:
* ro.fortsoft.pf4j.demo.api: https://paste.ubuntu.com/24007186/
* at.lyze.api: https://paste.ubuntu.com/24007188/

Log Diff: https://www.diffchecker.com/mDmlDaJw

MANIFEST.MF will get created properly in both cases:

    # Generated by PF4J
    ro.fortsoft.pf4j.demo.welcome.WelcomePlugin$WelcomeGreeting
    ro.fortsoft.pf4j.demo.welcome.WelcomePlugin$WelcomeGreeting

Project Files: 
* at.lyze: https://transfer.sh/2FDX9/at.lyze.zip
* ro.fortsoft.pf4j.demo: https://transfer.sh/jsvWo/ro.fortsoft.pf4j.demo.zip

**Comment by decebals** [comment]
First of all I want to say that it's probably one of the best issue report  which I have seen. :+1: 
It's for the first time then I see in PF4J that someone tries to create an extension class (annotated with `@Extension`) that implements multiple extension points. An issue is that we shouldn't have three entries/lines in `extensions.idx` (for `plugin2`) with same content.
Can you test the same approach with `Hallo` in `at.lyze.api` package but with three separate extensions in plugin2 (one extension class for each extension point)?

**Comment by lyze237** [comment]
I have the following setup now:

api: at.lyze.api.Hallo:

    public interface Hallo extends ExtensionPoint {
         public String getHallo();
    }


plugin1: ro.fortsoft.pf4j.demo.welcome.WelcomePlugin:

    @Extension
    public static class WelcomeGreeting implements Greeting {
    	@Override
        public String getGreeting() {
            return "Welcome";
        }
    }

    @Extension
    public static class WelcomeHallo implements Hallo {
        @Override
        public String getHallo() {
            return "Hallo";
        }
    }

I think the code should step into the if but it doesn't:
![iffail](https://cloud.githubusercontent.com/assets/11274700/23034348/d439d938-f47b-11e6-9609-d25d2517f796.png)

When I move the "at.lyze.api.Hallo" class back to "ro.fortsoft.pf4j.demo.welcome.Hallo" it works.

**Comment by decebals** [comment]
I don't see in first screenshot the value for `type` (on line `type.isAssignableFrom(extensionClass)`).

**Comment by lyze237** [comment]
Ah I'm sorry, here's a better screenshot with hopefully all variables.

![7hvxykz](https://cloud.githubusercontent.com/assets/11274700/23036000/819dfcc6-f481-11e6-836f-7b1b93ae134f.png)

**Comment by decebals** [comment]
`WelcomeHallo` implements `Hallo` and in normal situation Hallo.isAssignableFrom(WlecomeHallo) returns true but the problem (my feeling) is that you have two classes from different class loaders and from this reason that method returns true.
Can you verify to see if the class loader of type (Hallo) is the same with class loader of extension (WelcomeHallo)?

**Comment by lyze237** [comment]
For some reason it's not the same.

![ueiie7u](https://cloud.githubusercontent.com/assets/11274700/23036811/7ac9d3e0-f484-11e6-94d4-86b9673366c8.png)

**Comment by decebals** [comment]
If the response is that extension and extension point are loaded with different class loader. then please see https://github.com/decebals/pf4j/issues/110#issuecomment-244309598 and [this](https://github.com/decebals/pf4j/blob/master/demo/api/pom.xml#L32) line in pom.xml of Maven.

**Comment by lyze237** [comment]
Ah thank you, works now when I remove the api jar!

I should have read the Troubleshooting page more clearly, sorry.

**Comment by decebals** [comment]
No problem. You are welcome.
