### ISSUE TITLE
ExtensionsInjector and early PluginManager  early bean loading

### ISSUE THREAD

**Issue by ramymagdy** [decebals/pf4j#126]
In the ExtensionsInjector.postProcessBeanFactory function we are getting the PluginManager through the beanFactory.getBean(PluginManager.class); function given that in the BeanFactoryPostProcessor interface it was specifically mentioned that:
> A BeanFactoryPostProcessor may interact with and modify bean definitions, but never bean instances. Doing so may cause premature bean instantiation, violating the container and causing unintended side-effects. If bean instance interaction is required, consider implementing BeanPostProcessor instead.

And that is the actual case , since in the PluginManager we wish to get a hold of the applicationContext in order to set it as the parentContext for the Plugin, but we are not able to do so due to the early loading of the PluginManager bean.

**Comment by decebals** [comment]
Do you have a suggestion?

**Comment by decebals** [comment]
Is it a solution to pass the `PluginManager` instance in the constructor of `ExtensionsInjector`?

```java
@Configuration
public class SpringConfiguration {

    @Bean
    public PluginManager pluginManager() {
        PluginManager pluginManager = new DefaultPluginManager() {

            @Override
            protected ExtensionFactory createExtensionFactory() {
                return new SpringExtensionFactory(this);
            }

        };
        pluginManager.loadPlugins();

        // start (active/resolved) the plugins
        pluginManager.startPlugins();

        return pluginManager;
    }

    @Bean
    public static ExtensionsInjector extensionsInjector() {
//        return new ExtensionsInjector();
        return new ExtensionsInjector(pluginManager()); // <-- HERE
    }

    ...
}
```

**Comment by ramymagdy** [comment]
Well the Only solution that worked for me is not not create the PluginManager as a bean from the first place.

This is a normal service class that get the ApplicationContext and the BeanFactory and it does the same class loading as in the ExtensionsInjector

```
@Service
public class SpringPluginStarter {
	
	@Inject
	private ApplicationContext applicationContext;
	
	@Inject
	private AbstractAutowireCapableBeanFactory beanFactory;
	
	private static final Logger log = LoggerFactory.getLogger(SpringPluginStarter.class);

	@PostConstruct
	public void init() {
		
		initExtensionInjector();
	}
	
	public void initExtensionInjector() {
		SpringPluginManager pluginManager = new SpringPluginManager();
		pluginManager.loadPlugins();
		pluginManager.startPlugins();
		pluginManager.setApplicationContext(applicationContext);
        ExtensionFactory extensionFactory = pluginManager.getExtensionFactory();

        // add extensions from classpath (non plugin)
        Set<String> extensionClassNames = pluginManager.getExtensionClassNames(null);
        for (String extensionClassName : extensionClassNames) {
            try {
                log.debug("Register extension '{}' as bean", extensionClassName);
                Class<?> extensionClass = getClass().getClassLoader().loadClass(extensionClassName);
                beanFactory.registerSingleton(extensionClassName, extensionFactory.create(extensionClass));
            } catch (ClassNotFoundException e) {
                log.error(e.getMessage(), e);
            }
        }

        // add extensions for each started plugin
        List<PluginWrapper> startedPlugins = pluginManager.getStartedPlugins();
        for (PluginWrapper plugin : startedPlugins) {
            log.debug("Registering extensions of the plugin '{}' as beans", plugin.getPluginId());
            extensionClassNames = pluginManager.getExtensionClassNames(plugin.getPluginId());
            for (String extensionClassName : extensionClassNames) {
                try {
                    log.debug("Register extension '{}' as bean", extensionClassName);
                    Class<?> extensionClass = plugin.getPluginClassLoader().loadClass(extensionClassName);
                    beanFactory.registerSingleton(extensionClassName, extensionFactory.create(extensionClass));
                } catch (ClassNotFoundException e) {
                    log.error(e.getMessage(), e);
                }
            }
        }
	}
```

SpringPluginManager is just an extension of the DefaultPluginManager that have an applicationContext field

```
public class SpringPluginManager extends DefaultPluginManager {
	
	
	private ApplicationContext applicationContext;
	
	@Override
	protected ExtensionFactory createExtensionFactory() {
		
		return new SpringExtensionFactory(this);
	}
	
	
	
	public ApplicationContext getApplicationContext() {
		return applicationContext;
	}

	


	public void setApplicationContext(ApplicationContext applicationContext) {
		this.applicationContext = applicationContext;
	}	
}
```

Then in the class that extends the SpringPlugin createApplicationContext function

```
@Override
	protected ApplicationContext createApplicationContext() {
    	if (applicationContext != null) {
    		return applicationContext;
    	}
    	
		applicationContext = new AnnotationConfigWebApplicationContext();
		applicationContext.setParent(((SpringPluginManager) getWrapper().getPluginManager()).getApplicationContext());
		applicationContext.setClassLoader(getWrapper().getPluginClassLoader());
		applicationContext.refresh();
		return applicationContext;
	}
```

That was the only way where the wiring in my controller in the plugin managed to work with beans from the main application

**Comment by decebals** [comment]
Moved to https://github.com/decebals/pf4j-spring/issues/3.

**Comment by ramy-siha** [comment]
@laurentkvb 
I've attached a sample spring boot application, basically I guess the trick is in the WebConfigurer class

`@Configuration
public class WebConfigurer extends WebMvcConfigurerAdapter {
	
	@Autowired
	private SpringPluginStarter springPluginStarter;

}
`
That makes a dependency on the SpringPluginStarter, so that we make sure that the Plugin's has been initialized *before* creating the request mapping

I've attached a sample Spring Boot application that demonstrates it and modified the sample plugin2.
[plugin2.zip](https://github.com/pf4j/pf4j/files/1996771/plugin2.zip)


[demo.zip](https://github.com/pf4j/pf4j/files/1996760/demo.zip)

**Comment by laurentkvb** [comment]
@ramy-siha 

Thanks for providing an actual good example of it to load the plugincontroller at boot. 

Is it possible to create this bean at runtime? I'd like to do this at runtime also

**Comment by MatthiasDM** [comment]
> @laurentkvb I've attached a sample spring boot application, basically I guess the trick is in the `WebConfigurer class
> 
> ```java
> @Configuration
> public class WebConfigurer extends WebMvcConfigurerAdapter {
> 	
>     @Autowired
>     private SpringPluginStarter springPluginStarter;
> 
> }
> ```
> 
> That makes a dependency on the `SpringPluginStarter`, so that we make sure that the Plugin's has been initialized _before_ creating the request mapping
> 
> I've attached a sample Spring Boot application that demonstrates it and modified the sample plugin2.
> 
> [plugin2.zip](https://github.com/pf4j/pf4j/files/1996771/plugin2.zip) [demo.zip](https://github.com/pf4j/pf4j/files/1996760/demo.zip)

I know this may be an old comment, but after three days looking for an answer, this finally solved my problem. Spring-boot-starter-web + pf4j-spring + the use of restcontrollers and swagger via springdoc.  So thank you.
