### ISSUE TITLE
Interpretation of "requires" when exactly x.y.z

### ISSUE THREAD

**Issue by janhoy** [decebals/pf4j#142]
Today the `PluginDescriptor` and pf4j-update's `PluginInfo` takes a `requires` in string format and converts it into an expression when enforcing, using `ExpressionParser.parse()`.

My question/suggestion is in the case where developer does not enter an expression like `2.x` or `1.0 - 3.1` but enters an exact x.y.z version e.g. `2.3.1`, should that be taken literally so the plugin will only start with exactly that version, or should we rewrite that corner case into meaning `>=2.3.1` or less extreme `^2.3.1` (which is effectively 2.3.1-2.4.0)? 

Projects should of course educate plugin writers. But perhaps the framework could benefit from some kind of global configuration option e.g. `interpretExactRequiresAsMinVersion` defaulting to false?

**Comment by decebals** [comment]
Do you have a preference? I don't have a preference but I think that solution with a property/method that will be evaluated in PF4J is a very good idea; we could choose the right default (I don't know if this value could be `exactVersion` on false or true).

**Comment by janhoy** [comment]
I see that for OSGi, the `Import-Package` version is interpreted as the given version or later, see https://www.ibm.com/support/knowledgecenter/en/SSEQTP_8.5.5/com.ibm.websphere.osgi.doc/ae/ra_bundle_mf.html

Don't know either what should be the default. It should be mentioned in release notes anyway....

**Comment by decebals** [comment]
It's good to have the possibility to customize this behavior. For this reason, I prefer to move the logic of `validFor` method and creation of Expression from String, outside of `PluginDescriptor` class (for example in `AbstractPluginManager.isPluginValid`). So, the class that knows how to create an Expression from String for requires (or other fields) is PluginManager. In this mode anybody can extend the plugin manager and force a custom behavior. 
My two cents.

**Comment by janhoy** [comment]
Good point. Again, the `validFor` API is not yet released, so it should be safe to move it..
