### ISSUE TITLE
Failed to execute goal on project pf4j-demo-api

### ISSUE THREAD

**Issue by sinyat** [decebals/pf4j#147]
I checked this URL:[https://oss.sonatype.org/content/repositories/snapshots/ro/fortsoft/pf4j/pf4j/1.4.0-SNAPSHOT/](https://oss.sonatype.org/content/repositories/snapshots/ro/fortsoft/pf4j/pf4j/1.4.0-SNAPSHOT/)
The web directory does not exist

**Comment by decebals** [comment]
https://github.com/decebals/pf4j#how-to-build
Run `mvn clean install` from `pf4j` first. After this run demo.

If you want to run demo from command line please see https://github.com/decebals/pf4j#demo

**Comment by decebals** [comment]
@sinyat Any progress? May I close the issue?

**Comment by sinyat** [comment]
@decebals Yeah,you can close
