### ISSUE TITLE
Gradle demo is broken.

### ISSUE THREAD

**Issue by PatrickDattilio** [decebals/pf4j#157]
It seems that the gradle demo is currently broken, and it seems to stem from the `createPluginsRoot()` method of `AbstractPluginManager`.

```
protected Path createPluginsRoot() {
        String pluginsDir = System.getProperty("pf4j.pluginsDir");
        if (pluginsDir == null) {
            if (isDevelopment()) {
                pluginsDir = "../plugins";
            } else {
                pluginsDir = "plugins";
            }
        }

        return Paths.get(pluginsDir);
    }
```
Tossing a breakpoint in this method and checking Paths.get(".").toFile() , we can see that we are in the top level of the project, not the `app` module.  `plugins` refers to our actual plugins module, not `app/plugins` and "../plugins" does not exist. 

I'm not sure the best way to fix the demo. Using `DefaultPluginManager(Paths.get("app/plugin")) should get things working for development, but it breaks the nice DEVELOPMENT/DEPLOYMENT mode, and requires me to deploy an "app/plugin" folder with my project instead of the more user friendly "plugins"

**Comment by decebals** [comment]
I don't use Gradle in my projects but my feeling is that is not about gradle. Probably you have the same problem if you are not use gradle, it's a problem about runtime environment.
Possible solutions:
- set the working directory to "app" (`cd app`, `./my-run-app.sh`)
- create some symbolic links in file system to meet the expected directories layout
- set `pf4j.pluginsDir` system property (at runtime via `-Dpf4j.pluginsDir` on java command line or using System.setProperty(""pf4j.pluginsDir"")).
If you use `System.setProperty` approach in your main class, you could use the DEVELOPMENT/DEPLOYMENT mode, like in below pseudocode:
```java
public class MainClass {

    public static void main(String[] args) {
        String pluginsDir = System.getProperty("pf4j.pluginsDir");
        if (pluginsDir == null) { 
            if (isDevelopment()) { // you can check system property `pf4j.mode`
                pluginsDir = "../plugins";
            } else {
                pluginsDir = "plugins";
            }
            System.setProperty("pf4j.pluginsDir", pluginsRoot);

            PluginManager pluginManager = new DefaultPluginManager();
            pluginManager.loadPlugins();
            pluginManager.startPlugins();
        }
    }

}
```
- override `createPluginsRoot()` in your custom `PluginManager` (for example `MyPluginManager extends DefaultPluginManager `)

**Comment by janhoy** [comment]
@PatrickDattilio did this solve your question, so we can close this issue?
