### ISSUE TITLE
Loading Plugin with custom Constructor

### ISSUE THREAD

**Issue by Magnusgaertner** [decebals/pf4j#181]
Is it possible to pass constructor arguments on loading plugins? Or is it only possible to load plugins using the default constructor of the plugin.

Best regards
Magnus

**Comment by decebals** [comment]
>     /**
>      * Constructor to be used by plugin manager for plugin instantiation.
>      * Your plugins have to provide constructor with this exact signature to
>      * be successfully loaded by manager.
>      */
>     public Plugin(final PluginWrapper wrapper) {
>         ...
>     }
> 

https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/Plugin.java#L40

**Comment by decebals** [comment]
I don't know your use case. 
I think that you can use the pull approach instead of push for arguments.
An idea is to create your Plugin concept (`AcmePlugin extends Plugin`) and use something like `(MyPluginManager) getPluginWraper().getPluginManager()).getArguments()` or something similar.

**Comment by Magnusgaertner** [comment]
Thanks for the fast reply and elaborating a solution :)
