### ISSUE TITLE
Bug in FileUtils while creating URI on Windows

### ISSUE THREAD

**Issue by Julieng50** [decebals/pf4j#184]
Hi !
There is a bug in the method : 

```
    // org.pf4j.util.FileUtils line 216
    public static Path getPath(Path path, String first, String... more) throws IOException {
        URI uri = path.toUri();
        if (isJarFile(path)) {
            uri = URI.create("jar:file:" + path.toString());
        }

        return getPath(uri, first, more);
    }
```

You must force "\\" to "/" while doing `path.toString()` for Jar files.

The error is : 
Illegal character in opaque part at index 11: jar:file:D:\Dev\WorkingDir\projectName\plugins\plugin-pluginName.jar

**Comment by decebals** [comment]
Use `2.1.0-SNAPSHOT`.

**Comment by Julieng50** [comment]
Thanks for your reactivity :)
