### ISSUE TITLE
Bug in FileUtils for Jar files on Windows

### ISSUE THREAD

**Issue by Julieng50** [decebals/pf4j#185]
Hi !
After resolving the issue #184 
There is another bug : 
```
    // org.pf4j.util.FileUtils.java
    public static Path getPath(Path path, String first, String... more) throws IOException {
        URI uri = path.toUri();
        if (isJarFile(path)) {
            // FIXME : Another process needed
            uri = URI.create("jar:file:" + path.toString().replace("\\", "/"));
        }

        return getPath(uri, first, more);
    }

    public static Path getPath(URI uri, String first, String... more) throws IOException {
        // Exception thrown here
        FileSystem fileSystem = FileSystems.newFileSystem(uri, Collections.<String, String>emptyMap());

        return fileSystem.getPath(first, more);
    }
```
On the FIXME above, you need to check if the path "D:\Dev\WorkingDir\projectName\plugins\plugin.pluginName-1.0.0.jar" starts with "/" and add it if not.
Without "/", an Exception is thrown while creating the FileSystem : java.lang.IllegalArgumentException: URI is not hierarchical.

NB : As i said in #184, tests are failing :)
Thanks.

**Comment by decebals** [comment]
Can you supply a PR please. I use linux and you can reproduce easy the issue on your machine. If you can, please fix the test. Thanks!

**Comment by Julieng50** [comment]
PR done for fixing the bug.

For the tests I think the problem is : 

```
    // org.pf4j.DefaultPluginRepositoryTest.java
    @Before
    public void setUp() throws IOException {
        testFolder.newFolder("plugin-1");
        // Prove that we can delete a folder with a file inside
        Files.createFile(Paths.get(testFolder.getRoot().getAbsolutePath()).resolve("plugin-1").resolve("myfile"));
        // Create a zip file for plugin-1 to test that it is deleted when plugin is deleted
        Files.createFile(Paths.get(testFolder.getRoot().getAbsolutePath()).resolve("plugin-1.zip"));
        testFolder.newFolder("plugin-2");
        testFolder.newFolder("plugin-3");
    }
```
The line `Files.createFile(Paths.get(testFolder.getRoot().getAbsolutePath()).resolve("plugin-1.zip"));` is creating a fake zipfile. While reading, the file is corrupted so the test `testGetPluginArchives()` only see 2 plugins and not 3.

**Comment by decebals** [comment]
On my machine and Travis CI the test doesn't fail.

**Comment by decebals** [comment]
I will close this issue. I added a note about tests (my previous comment).
