### ISSUE TITLE
DefaultPluginManager.createPluginDescriptorFinder() should return PluginDescriptorFinder

### ISSUE THREAD

**Issue by wuruoyun** [decebals/pf4j#188]
Currently `DefaultPluginManager.createPluginDescriptorFinder()` API returns `CompoundPluginDescriptorFinder`. It should return the general `PluginDescriptorFinder` instead (as defined in `PluginManager` interface).

A use case is to extend `DefaultPluginManager` and use a custom `PluginDescriptorFinder` that is not of type `CompoundPluginDescriptorFinder`.

**Comment by decebals** [comment]
It was a mistake in 2.0.0. The code is fixed already on head.

**Comment by decebals** [comment]
See a30c05b.

**Comment by wuruoyun** [comment]
That is great! Thank you very much!
