### ISSUE TITLE
Allow multiple versions of the same plugin

### ISSUE THREAD

**Issue by wuruoyun** [decebals/pf4j#189]
It will be nice to allow multiple versions of the same plugin (in terms of plugin ID). For example, a software may install multiple versions of an algorithm plugin, and user may switch between different versions of the algorithm using a user-configurable settings. 

Currently `AbstractPluginManager` stores `plugins` and `pluginClassLoaders` in a Map with `pluginId` as the key, which makes the above impossible. A workaround is to explicitly append the version to `pluginId` when building the plugin, like "welcome-plugin-1.0.0", so that I can have both "welcome-plugin-1.0.0" and "welcome-plugin-1.1.0" installed at the same time. It will be nice to just define the id as "welcome-plugin" for both 1.0.0 and 1.1.0 and able to install them both.

**Comment by decebals** [comment]
Your use case is a little bit uncommon for me. 
A plugin comes with new extensions and/or extension points. So, you have an extension point, the `Algorithm` interface (or abstract class), and multiple implementations (extensions).  You can have one extension per plugin or multiple extensions in a plugin. 
I don't understand why you need the same algorithm in different versions. For me each algorithm (implementation) is a different, so we have one extension for each algorithm implementation.
You can display all available algorithms in a combo box, and the user can choose the desired algorithm. Your application saves the chosen algorithm and used it in application.

Make sense for you what I say?

**Comment by wuruoyun** [comment]
I agree it is a bit uncommon. For an example, we have "algorithm-plugin" 1.0. Sometime later we have 1.1. Most of the user may want to upgrade to 1.1, but some users may want to continue using 1.0 for some data and 1.1 for other data, based on certain conditions. In order to show both 1.0 and 1.1 of "algorithm-plugin" in a dropdown, both plugins needs to be at least "resolved".

Actually, if another issue #188 can be resolved, one can actually customize the PluginDescripterFinder to register resolved plugins with "<pluginId>-<pluginVersion>" as the key to the map in AbstractPluginManager. This should be good enough for what I need. :)

**Comment by decebals** [comment]
#188 is resolved. You can use in your system the approach explained b you in the end of your previous comment.
Again, I feel that you don't use correctly the concept of plugin, extension point and extension. It's a key step (and no easy) when you write a modular application to identify the plugins and the extensions points.
I will close this issue because you have an workaround. Please reopened it if you need more support,

**Comment by svarma11** [comment]
Hi how i can load the multiple class from the plugin. Currently we specify the class name which needs to be loaded runtime from the pluging , but what if we have multiple class in one plugin and all needs to be loaded, where and how to specify

**Comment by wuruoyun** [comment]
I suggest define an interface for your “multiple classes” and put each of them into their own plugin. At runtime each class will then be loaded by different class loader.

If the client of your “multiple classes” is itself a plug-in, probably you can define the interface in the host, and let the host passes the loaded class instance to that client.
