### ISSUE TITLE
Issue with demo_gradle

### ISSUE THREAD

**Issue by PureCS** [decebals/pf4j#192]
Hello, I am trying to get the demo to work and need some help.

I am trying to run `app` within IntelliJ to debug the program. It looks for the folder `plugins` in `app` so it doesn't find the external plugins.

Is there a way for the plugins directory to automatically update, depending on if the program is being debugged or not?

Kind regards

**Comment by decebals** [comment]
I don't use Gradle but I use IntelliJ.
Below is the configuration used by me when I run demo from IntelliJ.
![image](https://user-images.githubusercontent.com/1248311/34981818-5aa3c10a-fab1-11e7-9378-5eb8979ec279.png)

**Comment by PureCS** [comment]
I decided to change the output plugins directory, this was done in the root gradle build file using `
ext.pluginsDir = childProjects['$projname'].projectDir.path + '/plugins/'` where `$projname` is the project I wanted it to be in. I appreciate your response.
