### ISSUE TITLE
Field 'id' cannot be empty

### ISSUE THREAD

**Issue by qianlifeng** [decebals/pf4j#193]
Hi, I write a plugin , but it seems `getManifestPath` in `ManifestPluginDescriptorFinder` find the wrong manifest file. 

I have tested on Mac and Windows, it will find the manifest file in classes folder, which is the right one. but on linux, it finds the wrong manifest. The plugin zip is built with gradle.

![image](https://user-images.githubusercontent.com/1725475/34991162-891ae03e-fb03-11e7-89c6-099d50d9dc61.png)

![image](https://user-images.githubusercontent.com/1725475/34991073-44dc7d9c-fb03-11e7-8bae-de67539bc287.png)

![image](https://user-images.githubusercontent.com/1725475/34991127-6c6b37d6-fb03-11e7-96ee-fa20aeb1d0f4.png)

**Comment by decebals** [comment]
What version? If you use the last version (`2.1.0`) can you test using `2.0.0` version? Maybe #184 or #185 introduced a bug in `2.1.0`.
Thanks!

**Comment by decebals** [comment]
I think that correct location should be `plugin\META-INF\MANIFEST.MF` (standard location in a jar file). 
A directory based (as layout) plugin is a folder obtained via `unzip plugin.jar` (or plugin.zip).
It make sense?

**Comment by decebals** [comment]
A question: why you have thow manifest files in your plugin directory? It's strange. You should have only one manifest file.
By the way, the code responsible for finding manifest in the plugin directory is https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/ManifestPluginDescriptorFinder.java#L84.

**Comment by decebals** [comment]
Any resolution/news? Did you succeed in the end?

**Comment by qianlifeng** [comment]
Sorry for the delay, I clone and build [pf4j gradle demo](https://github.com/decebals/pf4j/tree/master/demo_gradle/plugins), it also has two manifest, one for java lib manifest and the other one is generated by gradle zip task I think.
```
task plugin(type: Jar) {
    baseName = "plugin-${pluginId}"
    into('classes') {
      with jar
    }
    into('lib') {
      from configurations.compile
    }
    extension('zip')
  }
```

When manifest solution fails, I tried plugin.properties solution.  Manifest.MF still get generated, but without plugin info, only Manifest-Version in it.

```
Manifest-Version: 1.0
```

The question here should be: why I have two manifest file. In above plugin gradle task, maybe it should exclude the manifest somehow. I tried few solutions but didn't success.

In the end, thanks to the scalability of pf4j, I customize the the PropertiesPluginDescriptorFinder to resolve the correct path. Not best solution, but it solves my problem 😅 
```
public class MonitorXPropertiesPluginDescriptorFinder extends PropertiesPluginDescriptorFinder {

    @Override
    protected Path getPropertiesPath(Path pluginPath, String propertiesFileName) throws PluginException {
        if (Files.isDirectory(pluginPath)) {
            return pluginPath.resolve(Paths.get("classes", propertiesFileName));
        } else {
            // it's a jar file
            try {
                return FileUtils.getPath(pluginPath, propertiesFileName);
            } catch (IOException e) {
                throw new PluginException(e);
            }
        }
    }
}
```

**Comment by decebals** [comment]
Can we close the issue?

**Comment by daberkow** [comment]
I still see the two MANIFEST files, and the first one, from the root of the plugin "META-INF/MANIFEST.MF" doesnt contain info in Gradle. My fix has been to declare it in the jar and in the plugin root.

`
jar {
    manifest {
        attributes 'Plugin-Class': "${pluginClass}",
            'Plugin-Id': "${pluginId}",
            'Plugin-Version': "${version}",
            'Plugin-Provider': "${pluginProvider}"
    }
}

task plugin(type: Jar) {

        manifest {
            attributes 'Plugin-Class': "${pluginClass}",
                'Plugin-Id': "${pluginId}",
                'Plugin-Version': "${version}",
                'Plugin-Provider': "${pluginProvider}"
        }


    baseName = 'BuildPlugin'
    into('classes'){
        with jar
    }
    into('lib'){
        from configurations.compile
    }
    extension('zip')
}
`

**Comment by DiCrEn** [comment]
Thanks @daberkow, that works. I only have this issue on linux, on windows pf4j gradle demo works perfectly for me.

**Comment by AkbarKazimov** [comment]
> I still see the two MANIFEST files, and the first one, from the root of the plugin "META-INF/MANIFEST.MF" doesnt contain info in Gradle. My fix has been to declare it in the jar and in the plugin root.
> 
> ```
> jar {
>     manifest {
>         attributes 'Plugin-Class': "${pluginClass}",
>             'Plugin-Id': "${pluginId}",
>             'Plugin-Version': "${version}",
>             'Plugin-Provider': "${pluginProvider}"
>     }
> }
> ```
> 
> ```
> task plugin(type: Jar) {
>         manifest {
>             attributes 'Plugin-Class': "${pluginClass}",
>                 'Plugin-Id': "${pluginId}",
>                 'Plugin-Version': "${version}",
>                 'Plugin-Provider': "${pluginProvider}"
>         }
>     baseName = 'BuildPlugin'
>     into('classes'){
>         with jar
>     }
>     into('lib'){
>         from configurations.compile
>     }
>     extension('zip')
> }
> ```

Thank you

**Comment by daberkow** [comment]
I jumped ahead to Gradle 7, and some things have changed. Incase it helps anyone else, I found removing the "into('lib'){" line made everything work and fixed my issue. configurations.compile does not exist anymore, so it gives...

> FAILURE: Build failed with an exception.
>* What went wrong:
Could not determine the dependencies of task ':plugin'.
> Resolving dependency configuration 'implementation' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'implementation' should be resolved.

```
task plugin(type: Jar) {
        manifest {
            attributes 'Plugin-Class': "${pluginClass}",
                'Plugin-Id': "${pluginId}",
                'Plugin-Version': "${version}",
                'Plugin-Provider': "${pluginProvider}"
        }
    baseName = '${pluginId}'
    into('classes'){
        with jar
    }
//    into('lib'){
//        from configurations.compile
//    }
    extension('zip')
}
```
