### ISSUE TITLE
Adding a new PluginState "UNLOADED" may be useful.

### ISSUE THREAD

**Issue by HeartUnchange** [decebals/pf4j#198]
I have a questions about the [Plugin lifecycle](http://www.pf4j.org/doc/plugin-lifecycle.html)
When can the plugin be removed ? I mean the plugin Jar-file or folder can be removed by system, like by the command ```rm``` or ```del```, not only by the code.

In [AbstractPluginManager.java](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L299), there is a method , ```deletePlugin```, 
It requires the plugin **unload** by the method [unloadPlugin](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L248) first. 
```java
    @Override
    public boolean deletePlugin(String pluginId) {
        checkPluginId(pluginId);

        PluginWrapper pluginWrapper = getPlugin(pluginId);
        PluginState pluginState = stopPlugin(pluginId);
        if (PluginState.STARTED == pluginState) {
            log.error("Failed to stop plugin '{}' on delete", pluginId);
            return false;
        }

        if (!unloadPlugin(pluginId)) {
            log.error("Failed to unload plugin '{}' on delete", pluginId);
            return false;
        }

        Path pluginPath = pluginWrapper.getPluginPath();

        return pluginRepository.deletePluginPath(pluginPath);
    }
```
The method check the plugin-state and try to unload it.
So why not add a plugin state named ```UNLOADED``` to indicate the plugin can be remmoved and after the method ```unloadPlugin``` called? 

The ```deletePlugin``` can be simple if the new state added.
```java
    @Override
    public boolean deletePlugin(String pluginId) {
        checkPluginId(pluginId);

        PluginWrapper pluginWrapper = getPlugin(pluginId);
        PluginState pluginState = pluginWrapper.getPluginState();
        if (PluginState.UNLOADED == pluginState) {
            Path pluginPath = pluginWrapper.getPluginPath();
            return pluginRepository.deletePluginPath(pluginPath);
        }
        log.error("Plugin '{}' not unload, can't be deleted", pluginId);
        return false;
    }
```
And it can indicate the plugin will not be invoked.
And users also can remove the plugin file by system command.

**Comment by decebals** [comment]
I think that the actual code of `deletePlugin` is good. The idea is that you can call`directly  deletePlugin` method  on a started plugin. 

Example:
P1: **CREATED** -> **STARTED** - **STOPPED**

Plugin P1 is in state **STARTED** but you can delete it. In this case in `deletePlugin` we call internally `unloadPlugin` (to be sure that the plugin is unloaded) that call internally `stopPlugin` (to be sure that the plugin is stopped). So it's not necessary to call manually, in sequence, all this methods.

To be correct, I think that the actual code of `deletePlugin` contains a necessary call to `stopPlugin`, it would have been enough to call only `unloadPlugin` that internally call `stopPlugin`.

I don't know if we need to add a new UNLOADED state. Maybe the answer is yes. Maybe some applications want to retrieve notification when a plugin was unloaded. I don't know yet. 
In the end what means that a plugin is in unload state? Do we want to be possible to call again `loadPlugin` method on an unloaded plugin?

I think that it's time to review this part with plugin lifecycle and to try improve it if we see some issues.

**Comment by HeartUnchange** [comment]
Yes, I have changed my mind. **The ```Plugin lifecycle``` already is enough.** I make it complex. Code should be concise.

I attach a picture I draw to show my mind about  the ```Plugin lifecycle``` some days ago. If some one have the same idea, please mention me. Maybe I can change your mind too. 
![Plugin lifecycle](https://user-images.githubusercontent.com/8402502/35367758-0abc6366-01bb-11e8-8f5d-c77fdd3145ff.png)

**Comment by decebals** [comment]
@HeartUnchange Nice diagram 😄.

If I have some time, and they are not reported new issues/bugs, I wish to try ti improve this zone.
In one of my [post](https://groups.google.com/forum/#!topic/pf4j/dxsYriVm2OA) on forum I enumerated two directions:
- plugin lazy loading (load a plugin - classes, jars); now all plugins are loaded on start application (the idea is to load a plugin only if I use extensions from that plugin)
- load plugins in parallel (if a plugin is not a dependency for another plugin)

They are valuable for medium or big applications with many plugins.
For example, right now all plugins are [loaded](https://github.com/decebals/pf4j/blob/a78fe6d7e6d9b11c2f2d8360ddf2d9cc13be7e8b/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L820) (a class loader is created and `PluginLoader.loadPlugin` method is called) before plugin validation (the plugin version are compatible with the version of application) and plugin resolving (all dependencies are available).

I am confident that actual high API is good, the framework is very configurable and all we must to do is to improve the actual implementation. Also we need to add more information in documentation because some nice feature exists but they are not documented. Plugin lifecycle is one of them.
As I said earlier in a previous comment, I will try to improve the plugin lifecycle aspects.

Thanks that invested time to understand the actual plugin lifecycle implementation.

**Comment by perlun** [comment]
> I don't know if we need to add a new UNLOADED state. Maybe the answer is yes. Maybe some applications want to retrieve notification when a plugin was unloaded. I don't know yet.

My 2 cents @decebals: I think an `UNLOADED` state would at least make some sense. The use case is this:

```java
// Custom PluginManager implementation which extends from DefaultPluginManager

addPluginStateListener( event -> {
    if ( event.getPluginState() == PluginState.STOPPED ) {
        unregisterModuleApplicationContext( event.getPlugin().getPluginId() );
    }
} );
```

This _works_, but what if we technically don't want to do this when a plugin is `STOPPED`, just when it's `UNLOADED`? At the moment, no can do; there is simply _no distinction_ from a `PluginStateEvent` point-of-view between a `STOPPED` and an `UNLOADED` event. This gives us things like this, which is a bit fishy. (Going from `STOPPED` to `STOPPED`, what does that even mean? :sweat_smile:)

![image](https://github.com/pf4j/pf4j/assets/630613/04829113-c8da-4cf1-a2f5-8851f94ce386)

**Comment by decebals** [comment]
> Going from STOPPED to STOPPED, what does that even mean?

This scenario was fixed https://github.com/pf4j/pf4j/commit/6e4e6b37818d00e685863c0eb3e40d47e6c7de90.

**Comment by slovdahl** [comment]
Hm, ok, so right now nothing will be posted when a module is actually unloaded? 🤔 Is adding such an event harder than something like this? Obviously some tests for it would be good too.

```diff
diff --git pf4j/src/main/java/org/pf4j/AbstractPluginManager.java pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
index 2f0d210..fb630ce 100644
--- pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
+++ pf4j/src/main/java/org/pf4j/AbstractPluginManager.java
@@ -298,6 +298,7 @@ public abstract class AbstractPluginManager implements PluginManager {
                 }

                 log.info("Unload plugin '{}'", getPluginLabel(pluginWrapper.getDescriptor()));
+                pluginState = PluginState.UNLOADED;
             } catch (Exception e) {
                 if (pluginWrapper == null) {
                     return false;
diff --git pf4j/src/main/java/org/pf4j/PluginState.java pf4j/src/main/java/org/pf4j/PluginState.java
index 989157f..a8e5afb 100644
--- pf4j/src/main/java/org/pf4j/PluginState.java
+++ pf4j/src/main/java/org/pf4j/PluginState.java
@@ -20,7 +20,7 @@ package org.pf4j;
  * <p>
  * Lifecycle of a plugin:
  * <pre>
- * CREATED -> RESOLVED -> STARTED -> STOPPED
+ * CREATED -> RESOLVED -> STARTED -> STOPPED -> UNLOADED
  * CREATED -> DISABLED
  * CREATED -> FAILED
  *
@@ -45,19 +45,24 @@ public enum PluginState {
     RESOLVED("RESOLVED"),

     /**
-     * The {@link Plugin#start()} has executed. A started plugin may contribute extensions.
+     * The {@link Plugin#start()} method has executed. A started plugin may contribute extensions.
      */
     STARTED("STARTED"),

     /**
-     * The {@link Plugin#stop()} has executed.
+     * The {@link Plugin#stop()} method has executed.
      */
     STOPPED("STOPPED"),

     /**
      * Plugin failed to start.
      */
-    FAILED("FAILED");
+    FAILED("FAILED"),
+
+    /**
+     * The plugin has been unloaded.
+     */
+    UNLOADED("UNLOADED");

     private final String status;
```

**Comment by slovdahl** [comment]
To put it more in context: our (mine and @perlun's) use-case is to make the `Plugin` classes be Spring beans. So we have a custom `PluginFactory` that creates the `Plugin` subclass and a Spring `ApplicationContext` and tie them together, and then we need a way for closing the Spring `ApplicationContext` when the plugin is unloaded. Right now we have overridden the whole `AbstractPluginManager#unloadPlugin(String pluginId, boolean unloadDependents)` method (we needed to do that for the workarounds described in #459) where can get the `Plugin` class before its `ClassLoader´ is closed and tear down the `ApplicationContext` in a proper way.

With #459 getting solved in pf4j itself, our idea was to use `PluginStateListener` for tearing down the `ApplicationContext` going forward, but without a proper `UNLOADED` event (or similar), we cannot do that.

I would be happy to submit a PR for this if you think it's worth adding.

**Comment by decebals** [comment]
> I would be happy to submit a PR for this if you think it's worth adding.

Please submit a PR. Now it's more clear what you want to achieve.

**Comment by perlun** [comment]
> To put it more in context: our (mine and @perlun's) use-case

Thanks for explaining this properly @slovdahl, appreciated. :pray:

**Comment by slovdahl** [comment]
> > I would be happy to submit a PR for this if you think it's worth adding.
> 
> Please submit a PR. Now it's more clear what you want to achieve.

#567
