### ISSUE TITLE
Make optional the plugin class attribute of plugin manifest

### ISSUE THREAD

**Issue by decebals** [decebals/pf4j#199]
Now, the plugin class attribute is [mandatory](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java#L877) but they are many scenarios when a plugin do nothing on start or stop method. Because the plugin class attribute is mandatory we I forced to create an empty plugin only to put something in the plugin class attribute.
My propose is to do optional the presence of plugin class in manifest by default.

This propose comes to simplify the creation of new plugins, in this mode we increase the adoption of our application plugin system. In the end, a plugin developer wants to add quickly a new functionality to the application and not to fight to understand the application plugin system (the application's extensions points list is enough as information). 
My wish is to see as many as possible small and medium Java modular applications and from this reason maybe the best motto for PF4J is **Modularity to people** :smile:.

**Comment by tylerhawkes** [comment]
The way I've been fixing this is by just having a default plugin that every other plugin uses. Adding a DefaultPlugin class to PF4J may ease adoption and it makes is to a parent pom can use the default class and modules can optionally implement a Plugin. 

If you do remove Plugin-Class from being required, I'd also request removing Plugin-Dependencies from being required and Plugin-Provider. Also, I've noticed that the maven-shade-plugin inserts `"null"` when properties aren't defined or they've been defined as `<plugin.dependencies />`, so also ignoring the string value `"null"` would be useful as well.

**Comment by decebals** [comment]
@tylerhawkes 
Now, only plugin id, plugin class and plugin version are mandatory. See https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/AbstractPluginManager.java. 
With this propose, if plugin class is missing, PF4J will create automatically for you an instance of `DefaultPlugin` (it's similar with put manually `DefaultPlugin` as plugin class in the plugin's descriptor file).

**Comment by decebals** [comment]
My final solution was to remove "abstract" classifier for `Plugin` class and to use this class by default when a plugin class is not supplied.
