### ISSUE TITLE
best practice design？

### ISSUE THREAD

**Issue by zhaoyta** [decebals/pf4j#201]
i have business  a,and have step s1,s2,s3,  i think each step is a extenpoint,  s1 have extension s11,s12.
and so ,s2->s21,s3->s31.

the plugin class define is 

public class a extends Plugin{

    .......

   @ Extension
   public static class s11 implements s1{
    ........
   }
   @ Extension
   public static class s12 implements s1{
    ........
   }

 @ Extension
   public static class s21 implements s2{
    ........
   }

@ Extension
   public static class s31 implements s3{
    ........
   }
} 

and then add to jar for a plugin .

is it right?or other best practice.

**Comment by decebals** [comment]
Looks good for me.
