### ISSUE TITLE
Spaces in name produce 'Illegal character in opaque part at index '

### ISSUE THREAD

**Issue by nonnamon** [decebals/pf4j#202]
Using spaces in the the plugin Jar causes ERROR log (but still loads) pf4j-2.2.0

Error logged: CompoundPluginDescriptorFindr.java71 - Illegal character in opaque part at index ... jar:file/./plugins/some file with spaces.jar

Logging ERROR, when plugin is still able to load and spaces in name are acceptable, is misleading

**Comment by decebals** [comment]
I will investigate but it's a bad practice to put spaces in a file name.
