### ISSUE TITLE
Make plugin configuration folders more flexible

### ISSUE THREAD

**Issue by lightglitch** [decebals/pf4j#31]
Support loading plugins from multiple folders.
Support plugin expand to a configured folder.

This allows to load plugins from program path (in program files in windows for example) but also from user profile folder for 3ª party plugins, the expand folder should be also on a profile folder. 

This permits to reset the installation by deleting the profile folder and also separate the plugin installations by user profile.

**Comment by decebals** [comment]
Sorry for delay. 

> Support loading plugins from multiple folders.
I think that this feature will be used very rare and complicate to much this framework. I wish to keep this framework as simple as possible. Sure it's possible to implement a custom `PluginManager` to accomplish this task (maybe it's a good idea to extract an `AbstractPluginManager` from `DefaultPluginManager` to simplify the implementation for a custom plugin manager.). PF4J is build using interface so it's relative easy to supply a custom implementation for all components.

> Support plugin expand to a configured folder.
Can be valuable.
 
Any PR or implementation pseudo code (draft) is welcome.

**Comment by decebals** [comment]
Can you close this issue?

**Comment by decebals** [comment]
I think that #43 resolves this issue.

**Comment by lightglitch** [comment]
Yep

**Comment by decebals** [comment]
Thanks for your contributions and sorry for my response time.
