### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by lightglitch** [decebals/pf4j#45]
We need to start having implementing this for the most important components. :)
Do you have some preferable approach?

**Comment by decebals** [comment]
:+1: 
Will be great to add some unit tests. I don't have a preferable approach, the standard approach (with all unit test in `pf4j/src/test/java/`) is ok. We must start with simple unit tests.
I am sure that we must make some modifications in the core for a better testability but I am ok.

**Comment by decebals** [comment]
We've already started.
