### ISSUE TITLE
Question: How to access an Extensions plugin?

### ISSUE THREAD

**Issue by defec8edc0de** [decebals/pf4j#52]
Hello,

A simple question:
I want to access the plugin-path stored in the plugin, from within the plugins extension.
Is this possible somehow?

Thanks for the great work.

**Comment by decebals** [comment]
Is https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/ro/fortsoft/pf4j/DefaultPluginManager.java#L559 what you are looking for?

**Comment by s3phir0th** [comment]
I tried to use it like this:

```
...
pluginManager.startPlugins();
myExtensions = pluginManager.getExtensions(IMyExtensionPoint.class);
for (IMyExtensionPoint currentExtension: myExtensions) {
            Plugin plugin = pluginManager.whichPlugin(currentExtension.getClass()).getPlugin();
            ...
}
...
```

and it couldn't find the plugin, to the extension (classloaders where not equal..)

If this helps:
My extensions extend a class: AbstractExtension (extends LogOutputStream implements IMyExtensionPoint)

**Comment by decebals** [comment]
I am in vacation. I will come back Monday.

**Comment by decebals** [comment]
So, your `MyExtension` is a `default` extension (it's declared in application not in a plugin)?

**Comment by s3phir0th** [comment]
`MyExtension` extends `AbstractExtension` extends `LogOutputStream` implements `IMyExtensionPoint` extends `ExtensionPoint` ....over a view inheritances its a default extension.

`MyExtension` is implemented as inner class of the Plugin.

**Comment by decebals** [comment]
@s3phir0th Did you solve this issue? I used `Plugin.whichPlugin` in [SpringExtensionFactory](https://github.com/decebals/pf4j-spring/blob/master/pf4j-spring/src/main/java/ro/fortsoft/pf4j/spring/SpringExtensionFactory.java) and everything seems OK.
