### ISSUE TITLE
Thread safety in PluginClassLoader

### ISSUE THREAD

**Issue by antonywarner** [decebals/pf4j#53]
Hi, we are starting to experiment with PF4J (thanks for the work by the way) and have come across a bug where the implementation of loadClass in PluginClassLoader is not thread safe. When we invoke it concurrently it tries to load the same class twice resulting in a LinkageError:

java.lang.LinkageError: loader (instance of ro/fortsoft/pf4j/PluginClassLoader): attempted duplicate class definition for name: "com/foo/MyExtension"
at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_80]

I notice that java.lang.ClassLoader#loadClass is made thread safe with a per class name lock:

protected Class<?> loadClass(String name, boolean resolve)
        throws ClassNotFoundException
    {
    synchronized (getClassLoadingLock(name)) {
        ...
    }
}

PluginClassLoader overrides that method and so loses that synchronized block. I think the fix is as simple as adding in a synchronized block? The getClassLoadingLock method is protected and so available to PluginClassLoader.

For now we have synchronised access to DefaultPluginManager.

**Comment by decebals** [comment]
I am in vacation. I will come back Monday.

**Comment by decebals** [comment]
Thanks for reporting this issue. The request for make pf4j thread safe appears also in #30. To be honest, I am not a specialist in java concurrency but I will try to do something in this direction.

**Comment by decebals** [comment]
I pushed a fix so you can test your application with the latest SNAPSHOT (now is 0.10.0-SNAPSHOT) via the Sonatype Maven Repository:

```
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```
