### ISSUE TITLE
DefaultPluginManager: pls. make "initialize()" overwriteable

### ISSUE THREAD

**Issue by tuxedo0801** [decebals/pf4j#69]
Hi there,

I would like to overwrite DefaultPluginManager#initialize() to change the log-message it produces and add some custom stuff etc., but it's "private". 

Please change...

Beside that, I really would welcome it to have more "protected" stuff in this class instead of "mostly private". The name *Default*PluginManager says it: It's a kind of default implementation that could be overwritten. But asking for each and every part of it to be changed to protected is boring...

I'm sure this can be applied to all "Default*" classes of pf4j ...

br,
Alex

**Comment by decebals** [comment]
I think that we have enough extension points for `DefaultPluginManager` (the factory methods `createXYZ(...)`). Are some situations when we must add other extension pointsbut I don't think that the `initialize` method is a good candidate.
The `initialize` method is only used in constructors so I think that it's better to override the constructors and to ignore `initialize` method if you want other implementation or to add new code after `super()`.
I don't understand why you want to replace the logging messages.

**Comment by tuxedo0801** [comment]
Agreed. Ignoring the initialize completely by using an own constructor is okay for me.
