### ISSUE TITLE
DefaultPluginManager#ceratePluginDescriptorFinder() not overwriteable

### ISSUE THREAD

**Issue by tuxedo0801** [decebals/pf4j#71]
The method is protected, so in general one can overwrite it. But it will require access to "pluginClasspath" field, which is "private". So it's hard to overwrite it without accessing this variable ...

**Comment by tuxedo0801** [comment]
In the meantime, I solved it with a reflection-hack. i added folling method to my own PluginManager:

```
    private PluginClasspath getPluginClasspath() {
        
        try {
            Class<? extends JarPluginManager> thisClazz = getClass();
            Field field = thisClazz.getField("pluginClasspath");
            
            field.setAccessible(true);
            PluginClasspath cp = (PluginClasspath) field.get(this);
            
            return cp;
        } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
            throw new RuntimeException("Cannnot access classpath variable!", ex);
        } 
    }
```

But I still vote for changing the implementation...

**Comment by decebals** [comment]
See https://github.com/decebals/pf4j/commit/eefe2341bd01991cbc342f910c0e2adf4ea3a28a. Please tell me if this commit help you.

**Comment by tuxedo0801** [comment]
Yes, looks good. My reflection-hack is no longer needed. thanks.
