### ISSUE TITLE
How do I make a plugin using maven without installing the whole example project?

### ISSUE THREAD

**Issue by Wicpar** [decebals/pf4j#74]
Hello,
I am new to pf4j and maven, and I tried my bet to find out how the hell it works, but i could't find a simple way to make plugin. There is no example plugin structure and i built the demo project with intelliJ, but that didn't help. As I want to let my program users the freedom to code plugin, i would like to know a way to make it Without maven or gradle, because they are quite confusing if you are new to it.
Please help me, I am stuck...

**Comment by decebals** [comment]
Hi,
I don't understand why you refuse to use a built tool (ant with ivy, or maven, or gradle). If you don't want to use a built tool you must define a project structure and add all `.jars` in a folder (for example `lib`). You must resolve all the project dependencies manually.
`PF4J` is a very light library with very few dependencies so I think you can download manually the artifact  (jar file) and all dependencies from [Maven Central Repository](http://mvnrepository.com/artifact/ro.fortsoft.pf4j/pf4j/0.10.0).
So click on "Download (JAR)" button to download `pf4j-xyz.jar` and repeat the operation for all dependency [java-semver](http://mvnrepository.com/artifact/com.github.zafarkhaja/java-semver/0.9.0) and [slf4j-api](http://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.5). Put these three files in your `lib` folder.
I don't know how you want to pack your plugins without a built tool (probable using a shell script) but I am sure that you find a solution.
Again, I think that using a built tool (maven for example) is the best solution but it's your choice.

**Comment by Wicpar** [comment]
Ok, thanks for your elp, I feel like i have been a bit harsh on the title, sorry for that. Thanks for your help, a more accurate question would have been, how do I use maven to make a plugin without needing to download the whole project?

**Comment by decebals** [comment]
Usually a developer can use a quickstart Maven archetype similar with [this](http://www.pippo.ro/dev/quickstart.html) but I don't know if it's possible to create a such Maven archetype for `PF4J` (of course any contribution is welcome).
My advice is to use the maven structure (with the `pom.xml` and `assembly.xml` files) from [demo](https://github.com/decebals/pf4j/tree/master/demo) project or to take a look before start your project. The demo project in my opinion is very light and you can learn many things from this project.

**Comment by Wicpar** [comment]
ok thanks :)
What I plan to use is the intelliJ built in tools, and since a day ago I understand maven quite a lot better. I think I will contribute a little tutorial on how to set up a plugin making environment using the IDE built in tools. I do not know what you use, but it seems maven is optimised for developping with generic text editors and javac, and is a bit less convenient than the built in tools of most modern IDEs. Thanks for your awesome project :)

**Comment by decebals** [comment]
Please don't forget to close this issue.
