### ISSUE TITLE
I made a IntelliJ project to easily make plugins. (ant based)

### ISSUE THREAD

**Issue by Wicpar** [decebals/pf4j#75]
# Hello!
In the last few days, trying to make plugins for this awesome library has been a lot of struggle, so since i planned to make a generic intelliJ project to easily make and test plugins with intelliJ, I thought I would give it to you and explain to you how to adapt it to your application. the project is avaliable to download here: https://mega.nz/#!4NtUDCwR!BZQbiernX8sAk-03mxKSyhlAPu2_v7tI0LLOYQYjLao
just unzip it an you will have a functional intelliJ project.
## But wait, Some configurations have to be done
first, you will notice a build.xml in the project folder. In my application, it necessitates a specific path to know where to put the plugin once it is packaged. To do so, you can either write it entirely instead of this:
```xml
<target name="package" depends="compile">
        <zip destfile="${plugin.path}/${plugin.id}-${plugin.version}.zip" basedir="out"/>
</target>
```
so it looks like this:
```xml
<target name="package" depends="compile">
        <zip destfile="Yourpath/zipname.zip" basedir="out"/>
</target>
```
or have this part modified:
```xml
<condition property="plugin.path" value="${user.home}/AppData/Roaming/rest of plugin path">
        <os family="windows"/>
    </condition>
    <condition property="plugin.path" value="${user.home}/Library/Application Support/rest of plugin path">
        <os family="unix"/>
    </condition>
```
into something like
```xml
<condition property="plugin.path" value="windows/path/to/your/plugin/folder">
        <os family="windows"/>
    </condition>
    <condition property="plugin.path" value="unix/path/to/your/plugin/folder">
        <os family="unix"/>
    </condition>
```
or if you do not care about os specificiality, just replace the condition lines as seen above by
```xml
<property name="plugin.path" value="Path/to/plugin/folder"/>
```
so that was the part for the output folder.
Now, there is something else to know:

the folder BaseLibs is there for the libraries that won't be included, put all libraries like pf4j, your applications library and the plugin dependencies in it.

the folder libs is the one that gets included for any additional 3rd party libraries used by your plugin, for instance an ASCII drawing api, cuz you like fancy ASCII art :)

Do not forget that intelliJ wont use them unless you specify them in file/project structure/libraries. Only referencing them there wont work either, they have to be in their corresponding libs folder and specified in intelliJ (for the autocompletion etc...).

Afterwards, you may want to modify the TestPlugin launch configuration, by telling him the path to your executable application jar, so you can instantly test you application by hitting the run button in IntelliJ.

Now just code your plugin in the src folder as you would normally do :)

## That's all Folks :)
Hope it helps and don't hesitate and modify it as you want so you can give your users an easy tool to work with the plugins (instead of this bunch of maven code salad the lib author gave us ;) )

**Comment by decebals** [comment]
Thanks! Please put this information on the [PF4J's mailing list](https://groups.google.com/forum/#!forum/pf4j).
