### ISSUE TITLE
weird code formatting

### ISSUE THREAD

**Issue by tuxedo0801** [decebals/pf4j#76]
I've seen this already a long time ago. But as more I am working with the source, the more annoying it gets...

Just an example. There are moe of this, some more, some less strange ...

![bildschirmfoto vom 2015-10-03 11 30 22](https://cloud.githubusercontent.com/assets/2862906/10262287/4cb0d9fc-69c2-11e5-9f44-ad9e3f9d9ac0.png)

Seems that the lin indent is broken? 
Some is "tab", some is "white space". 

Netbeans f.i. converts all indentation to white spaces...

Can this be fixed? Otherwise it's hard to read the code. I could format it locally with NB, but this will change the code and make fetchign code changes from GH more irritating...

**Comment by decebals** [comment]
I have impression that you have tab set to 8 spaces in NB. In Idea IntelliJ the file `ManifestPluginDescriptorFinder` looks OK.

**Comment by decebals** [comment]
I forgot to say that we use [editorconfig](http://editorconfig.org) to maintain consistent coding styles between different editors and IDEs. [Here](https://github.com/decebals/pf4j/blob/master/.editorconfig) is the code formatting style for PF4J.
I see now that exist a EditorConfig [Plugin](https://github.com/welovecoding/editorconfig-netbeans#readme) for NetBeans and maybe this plugin is useful in your case.

**Comment by tuxedo0801** [comment]
I don't see why I have to change my setup when *every* other opensource project looks good. It's just pf4j.

I will check more classes wrt. formatting to see if it's really the tab-setup.

**Comment by tuxedo0801** [comment]
Checked again the code...

It's not just a tab-configuration issue. 

The indentation is a wild mixture of
* just white spaces
* tabs
* white spaces AND tabs

![codeformatting](https://cloud.githubusercontent.com/assets/2862906/10331401/54ee7870-6cd5-11e5-8167-426310332868.png)

Modern IDEs convert tabs to white-spaces. Default in Eclipse and Netbeans is tab=4 white spaces.
If the used editor does not use another setting, I don't see the need for an extra tool like editorconfig to format the indentation (not talking about brackets etc..)

**Comment by decebals** [comment]
I see no problems in your last screenshot. Maybe you can show me the same screenshot type (with LF, TAB, ...) for `ManifestPluginDescriptorFinder` (your first screenshot with indentation problems).
Related to `editorconfig` I can copy/paste the aim of this tool:
> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

For example I use __Idea IntelliJ__ and I wish to have a unitary, minimal coding styles for this project which is not dependent on IDE used. If you have other recommendation please let me know.

**Comment by tuxedo0801** [comment]
You're right. Notepad++ (the screenshot from last post) is interpreting the tabs "correctly" (tab=4 spaces).
I was partly wrong in my last post wrt NB default behavior:

If I enter a "tab" in Netbeans IDE, it creates 4 whitespaces. 
If I open a file which has tab-control-character, it "interpretes" the tab with 8-whitespaces. 
That's why it looks so weird. 

Here's the screenshot you would like to see:

![codeformatting2](https://cloud.githubusercontent.com/assets/2862906/10333986/858edd32-6ce7-11e5-931c-0232dbc64973.png)


Left side: Netbeans with default settings: Tabs are presented with 8 whitespaces.
If I press myself the tab-key, it creates no tab-character, but 4 white spaces.

Right side: Same file, but shown in Notepad++ to make the controlcharacters visible.

Eclipse is using 4whitespaces for tabs and is not automatically inserting whitespaces when using tab-key (inserts tab-control-char).

My recommendation:
Eliminate tab-control-char by update your editorconfig setup to use 4 white-spaces instead of tab-control-character. With that setting, code indentation looks in every applicatrion/ide/editor identically.
And for those who work on the code can install editorconfig to ensure the same formatting on all systems.

**Comment by tuxedo0801** [comment]
Any comments on my recommendation?

**Comment by decebals** [comment]
We already use soft tabs via `indent_style = space` in `.editorconfig` but probably are some old code lines that don't respect this rule. I will make a test to see if a new code fragment respect this rule defined in .editorconfig.
