### ISSUE TITLE
PluginManager.disablePlugin -> UnsupportedOperationExeption

### ISSUE THREAD

**Issue by tnyblom** [decebals/pf4j#78]
When trying to disable a plugin without having a "disabled.txt" file in the plugins directory, DefaultPluginStatusProvider::disablePlugin() fails with an Exception.

As far as I can tell this is due to thet FileUtils::readLines returns Collections.emptyList() in case the files doesn't exist and DefaultPluginStatusProvider assigns this to disabledPlugins.

I assume the same would be true for enablePlugin.

/Cheers
Torgny
(Btw, nice framework :))

**Comment by tnyblom** [comment]
Thanks!

(This has to be the fastest reacting project of all times :))

**Comment by decebals** [comment]
Thanks! If you encounter other problems please let me know.
