### ISSUE TITLE
best practice: how plugin-A makes use of plugin-B?

### ISSUE THREAD

**Issue by tuxedo0801** [decebals/pf4j#79]
Hi there,

I have to plugins. A and B.

The running plugin B provides stuff which A has to use. This stuff is configured&started by PluginB#start() ...

I already set the dependency in plugin.properties, but I'm not sure what is the preferred way to access B from A without creating a new instance of B.

Any hints?

**Comment by tuxedo0801** [comment]
My current solution would be:

Have the pluginmanager static + a static "getPlugin()" which uses the pluginmanager to query the plugin.

And PluginA uses this static getter to get PluginB.

Is there a better way? Maybe extend the PluginWrapper so that one can query the underlying pluginmanager for other plugins?!

**Comment by decebals** [comment]
Can you give me more details about your use case (maybe some code) please.
You say that __plugin A__ depends on __plugin B__ and in __pluginB.start()__ method you create and configure a class (for example) that it's used in Plugin A, am I right?

**Comment by tuxedo0801** [comment]
That's correct. 

My usecase is:

Plugin A is serving a HTTP-Interface. A client can use this interface to interact with a homeautomation system. 
Plugin B is a cache-service-plugin. It reads on request data from homeautomation system, caches it and returns the requested value.
And Plugin A uses Plugin B to read (cached) values from homeautomation system.

The plan is, that plugin B is used primarily by Plugin A. But there will be more plugins that will use the cache-service of Plugin B.


My use of pf4j is less a classical "plugin-system that extends the main-application", but more a kind of application framework: The main application is only managing the lifecycle of the plugins (there is no extensionpoint at all). 
It's a kind of ultra-simple OSGI replacement ;-) 

At the moment I use the "static getter" to get access from any plugin to another plugin. Works for me.
Question is if this could be done via pluginwrapper. But for this, pluginwrapper needs to have a reference to pluginmanager, which is not yet in place.

**Comment by decebals** [comment]
I don't know if it's not a good idea to mark your `CacheService` as an extension point declared by Plugin B. Also, Plugin B comes with the implementation. In this mode you can use the `CacheService` in an elegant mode in other plugins.

Another idea is to create the yours __MyPluginManager__ that simple extends __DefaultPluginManager__ and implement the singleton pattern(`public static MyPluginManager getInstance();`). In this mode you can access the plugin manager from any plugin (or other code).

**Comment by tuxedo0801** [comment]
Using the extension-point is an idea, yes. But I still need access to the plugin-manager to access the extension.

Wouldn't it be a good idea to put an reference to the related pluginmanager to the pluginwrapper when loading the plugin?

**Comment by decebals** [comment]
Done, see commit c7d6a98d99.

**Comment by tuxedo0801** [comment]
Thanks. That makes life easier and prevents static getter/singletons...
