### ISSUE TITLE
hey men i cloned you project demo but it not work i get maven errors

### ISSUE THREAD

**Issue by sirlordt** [decebals/pf4j#80]
I using IDE eclipse Luna SR2 the problem is on 0.10.0-SNAPSHOT not found 

Description	Resource	Path	Location	Type
Missing artifact ro.fortsoft.pf4j:pf4j:jar:0.11.0-SNAPSHOT	pom.xml	/pf4j-demo-api	line 28	Maven Dependency Problem

**Comment by decebals** [comment]
> I using IDE eclipse Luna SR2 the problem is on 0.10.0-SNAPSHOT not found

Maybe 0.11.0-SNAPSHOT not found

What command you use? You cloned the demo project in a personal new project/folder? Try to run `mvn clean install` from pf4j folder (to install pf4j.jar in your local maven repository) and try again to build your project.

**Comment by decebals** [comment]
@sirlordt Any resolution for this issue?

**Comment by sirlordt** [comment]
Sorry i not try again, i busy another develop issues not related with this lib.

Thanks for your concern.
