### ISSUE TITLE
Release-Plan for 0.11.0?

### ISSUE THREAD

**Issue by tuxedo0801** [decebals/pf4j#81]
Hi there,

Is there any release plan for 0.11.0? 
My application currently depends on 0.11.0-SNAPSHOT and I'm interested when 0.11.0 will be released...

br,
  Alex

**Comment by decebals** [comment]
I haven't anything in pipe so I can release a new version if this it's important for you. I don't know if the next version must be 0.11.0 or 1.0.0. 

I wish to add more unit tests and more documentation but my time that can be allocated by me to this project is limited.

Related to new features I have an idea to add a possibility to document all extensions and extension points from a system (a list with all extensions points, extensions and associated javadoc for each plugin) but I don't think yet it's valuable for other users.

**Comment by tuxedo0801** [comment]
I don't care about the exact version number. main issue is the release so that I no longer need to depend on the non-snapshot-version which every one needs to build on his own ;-)

But if I where you, I would switch to 1.x if it's a big feature step or or something is no longer backwards-compatible. So for now, go with 0.11.0

**Comment by decebals** [comment]
Version 0.11.0 released.

**Comment by tuxedo0801** [comment]
Thanks a lot. Will test it.
