### ISSUE TITLE
Unable to detect Extensions

### ISSUE THREAD

**Issue by gsine** [decebals/pf4j#82]
I have followed the procedure outlined in the home page.
1. I have one plugin that is dropped into the plugins folder as a ZIP file.
When the EAR is deployed and starts up in Wildfly, I can see that the ZIP file is unzipped. The manifest seems to be correct, and the extensions.idx has the class name.
2. PF4J is able to read the plugin, and records that one possible extension is found.
3. However, when I try to getExtensions(), the error is that the type is not assignable from the extension Class.

Please let me know if you require any additional information to help me with this issue.

Thanks and Best Regards,
GPN

**Comment by decebals** [comment]
The log of pf4j is very detailed on debug and you can see where is the problem (you can see what classes are loaded by each plugin class loader).
I think that you have a class in many jars loaded with different class loaders.

**Comment by gitblit** [comment]
I think @decebals has the right of it here.  If you have a type `Foo` referenced by two classloaders, `Foo`  is not  instance-compatible between the two classloaders - leading to your not assignable error.  The only time this works is when the second classloader is a child of the first one AND it inherits/shares the parent classloader.

**Comment by gsine** [comment]
Sorry my bad.
This is a duplicate of the discussion here https://github.com/decebals/pf4j/issues/64.
I should have searched earlier before posting.
Thanks.

**Comment by decebals** [comment]
No problem. Maybe it's the time to add o possibility in code to detect these situations.

**Comment by Mukarr** [comment]
I am facing similar problem. @decebals How can access the logs for pf4j?

**Comment by decebals** [comment]
PF4J uses [SLF4J](http://www.slf4j.org/) for logging but you must add a concrete implementation in your project (pom.xml if you use Maven). For example PF4J Demo [uses](https://github.com/decebals/pf4j/blob/master/demo/app/pom.xml) Log4J as implementation.
