### ISSUE TITLE
Could You provider a demo of plugin.dependencies

### ISSUE THREAD

**Issue by darknessitachi** [decebals/pf4j#88]
for example:
- plugin-person
```java
    interface Person extends ExtensionPoint { ... }

    class PersonService {

        public List<Person> persons() {
            PluginManager pluginManager = ...;
            List<Person> persons = pluginManager.getExtensions(Person.class);
        }

    }
```

- plugin-student, plugin.dependencies=plugin-person
```java
    class Student implements Person { ... }
```
- plugin-teacher, plugin.dependencies=plugin-person
```java
    class Teacher implements Person { ... }
```

I'm trying this, but not success.

**Comment by decebals** [comment]
I don't understand what is wrong.

I see that you have 3 plugins:
- plugin-person
- plugin-student
- plugin-teacher

In __plugin-person__ you declare `Person` as an extension point. In __plugin-student__ you declare `Student`  as extension for `Person` and in __plugin-teacher__ you declare `Teacher` also as extension for `Person`. I suppose that you put `@Extension` annotation on these classes.

So, what is it wrong? Do you have exceptions or `pluginManager.pluginManager.getExtensions(Person.class)`  returns an empty list?

**Comment by decebals** [comment]
Some news?
