### ISSUE TITLE
Can't use ExtensionPoints from Plugins

### ISSUE THREAD

**Issue by lyze237** [decebals/pf4j#90]
Dear Developer,
I'm currently having a problem with your library.

Let's say we have a basic project with:

* core
* pluginApi
* plugins/globalOptions
* plugins/commandPlugin

Inside the "globalOptions" plugin I have this interface:

    package at.lyze.plugin.globalOptions.extensionpoint;
    import ro.fortsoft.pf4j.ExtensionPoint;

    public interface OptionHandlerExtension extends ExtensionPoint {
        void getOptions();
    }

And then I have a class in the same project which uses the interface:

    package at.lyze.plugin.globalOptions;

    public class GlobalOptions extends Plugin {
    @Extension
        public static class GlobalOptionsExtension implements OptionHandlerExtension {
            @Override
            public void getOptions() { … }
        }
    }

----

Now inside the other plugin "commandPlugin" I try to access all "OptionHandlerExtension" via

    List<OptionHandlerExtension> optionHandlers = wrapper.getPluginManager().getExtensions(OptionHandlerExtension.class);
            
But this doesn't return anything.

A temporary solution would be to move the Interfaces into the "pluginApi" project but I want to have that interface in the "globalOption" plugin.

Is there any way I could do this?

Edit: If you want to take a look at the full example: http://bitbucket.lyze.at/projects/DAR/repos/darkowlbot/browse
(Gradle build order would be: clean, jar, plugin, compilePluginsAndCopy, core:run)

**Comment by decebals** [comment]
I will take a look.

**Comment by decebals** [comment]
Any error in console/log ? Please run pf4j in development mode (`-Dpf4j.mode=development`) with pf4j log on debug and see (in console/log) if each plugin sees all extensions.

I see in
```java
@Extension
public static class GlobalOptionsExtension implements OptionHandlerExtension, SaveLoadExtension
```
that `GlobalOptionsExtension` is an extension for two extension points but I think that it's not a problem

**Comment by decebals** [comment]
> Please run pf4j in development mode (-Dpf4j.mode=development) with pf4j log on debug and see (in console/log) if each plugin sees all extensions

It's enough to put the pf4j log on debug.

**Comment by lyze237** [comment]
http://pastebin.com/3w42QeQf

That's the log when trying to run it and trying to get the optionhandlerextension interface.

Search for "warn" to see that there are 0 elements loaded.

What I find also interesting is, that the plugin tries to class '# Generated by PF4J' all the time which it can't find.

**Comment by decebals** [comment]
> What I find also interesting is, that the plugin tries to class '# Generated by PF4J' all the time which it can't find.

You use PF4J version 0.12 to compile the plugins and version 0.11 to run the plugins. Please use 0.12 in both situations.

**Comment by decebals** [comment]
Please post again the log on pastebin after you are sure that your application uses only pf4j 0.12

**Comment by lyze237** [comment]
Now when ever I try to launch it I have that error with "FileSystemAlreadyExistsException": http://pastebin.com/UUNz5aVM

Where do libraries go from plugins?
Do they need to get moved into the zip file or should they be loaded via the default classpath?
Do you need your libraries classes inside the zip plugins also?

**Comment by decebals** [comment]
Strange. Please use the last version from Github, version 0.13.0-SNAPSHOT. You can find more information about the build process at https://github.com/decebals/pf4j#how-to-build.
On the other side, I want to say you that I don't use Gradle in my project so maybe is something wrong in the assembly process of plugin zip. You can read more about the plugin structure at https://github.com/decebals/pf4j#how-to-use.
If the problem persist, please try to disable `ServiceProviderExtensionFinder`, component added in the last version. To do this you must override `DefaultPluginManager.createExtensionFinder()` and return `LegacyExtensionFinder`.

**Comment by lyze237** [comment]
Ah thanks.
Reverting back to "LegacyExtensionFinder" worked properly.
Also a little question regarding libraries.
Do we need to pack the class files from the libraries into "plugin.zip/lib" or do we need to put the jars into there?

**Comment by decebals** [comment]
PF4J is very customizable. [PluginLoader](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/ro/fortsoft/pf4j/PluginLoader.java) is the class that loads the plugin's byte code from a [PluginClassPath](https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/ro/fortsoft/pf4j/PluginClasspath.java).
By default the plugin classpath is `/lib/*.jar` and `/classes/*`.
Related to your question, I prefer the default implementation (put all external plugin's in `lib` folder and plugin's classes in `classes`) but you can pack your plugin and put it in `lib` folder (together with the plugin's external dependencies).
I hope that my response helps you.

**Comment by lyze237** [comment]
Ah yes, thanks.

I've added 2 pull requests:

* For the gradle example
* For the legacy plugin manager

Thanks for helping me getting your library to work, i really enjoy using it.
