### ISSUE TITLE
ServiceLoader interoperability problem

### ISSUE THREAD

**Issue by jchappelle** [decebals/pf4j#92]
I have my application working with ServiceLoader. I'm trying to cut over to PF4J and I'm not having any luck. I'm basing my assumptions on your "ServiceLoader interoperability" section where you state:

> if you have a modular application based on java.util.ServiceLoader class you can replace entirely the ServiceLoader.load() calls from your application with PluginManager.getExtensions() and migrate smooth from ServiceLoader to PF4J.

Here is what I have. I have created a facade for my application to use when loading Service interfaces.

```
public interface ExtensionProvider
{
    <T> List<T> getExtensions(Class<T> type);
}
```

I have an implementation that uses ServiceLoader like this:

```
public class ServiceLoaderExtensionProvider implements ExtensionProvider
{
    @Override
    public <T> List<T> getExtensions(Class<T> type)
    {
        List<T> result = new ArrayList<>();
        ServiceLoader.load(type).forEach(extension -> result.add(extension));
        return result;
    }
}

```

Now I have written a PF4J implementation like this:

```
public class PF4JExtensionProvider implements ExtensionProvider
{
    private final PluginManager pluginManager;

    public PF4JExtensionProvider()
    {
        //I think this is just for annotation processing, which we are not using at the moment(the services files are already in META-INF/services)
        System.setProperty("pf4j.storageClassName", "ro.fortsoft.pf4j.processor.ServiceProviderExtensionStorage");

        pluginManager = new DefaultPluginManager();
        pluginManager.loadPlugins();
        pluginManager.startPlugins();
    }

    @Override
    public <T> List<T> getExtensions(Class<T> type)
    {
        return pluginManager.getExtensions(type);
    }
}
```

My ExtensionProvider is defined as a Spring bean. I was hoping to just change the implementation to my PF4JExtensionProvider but that didn't work. So then, I tried making all my Service interfaces extend  the PF4J ExtensionPoint interface. Still no luck.

Any ideas or suggestions?

Thanks in advance!

**Comment by jchappelle** [comment]
Also, I just tried creating an ExtensionProvider that retrieves the PluginManager from the Wicket Application class. Still no luck.
```
public class WicketPF4JExtensionProvider implements ExtensionProvider
{
	@Override
	public <T> List<T> getExtensions(Class<T> type)
	{
		PluginManager pluginManager = (PluginManager)Application.get().getMetaData(PluginManagerInitializer.PLUGIN_MANAGER_KEY);
		return pluginManager.getExtensions(type);
	}
}
```
I have ro.fortsoft set to DEBUG. I see the following output:
```
10:19:26.849 [main]  INFO  org.apache.wicket.Application - [wicket.myapp-wicket] init: ro.fortsoft.wicket.plugin.PluginManagerInitializer@e1f88b6
10:19:26.850 [main]  DEBUG r.f.w.p.PluginManagerInitializer - Plugins directory is plugins 
10:19:26.851 [main]  DEBUG r.f.w.p.PluginManagerInitializer - Create default plugin manager
10:19:26.860 [main]  INFO  r.fortsoft.pf4j.DefaultPluginManager - PF4J version 0.12.0 in 'deployment' mode
10:19:26.865 [main]  INFO  r.f.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
10:19:26.865 [main]  INFO  r.f.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
10:19:26.867 [main]  DEBUG r.f.w.p.PluginManagerInitializer - Created plugin manager ro.fortsoft.pf4j.DefaultPluginManager@5d27a744
10:19:26.867 [main]  DEBUG r.fortsoft.pf4j.DefaultPluginManager - Lookup plugins in 'C:\eclipse-workspaces\mycompany\myapp-parent\myapp-wicket\plugins'
10:19:26.868 [main]  DEBUG r.fortsoft.pf4j.DefaultPluginManager - Found 0 possible plugins: []
10:19:26.869 [main]  INFO  r.fortsoft.pf4j.DefaultPluginManager - No plugins

```
The output is after I have created an empty plugins folder in my wicket project just to see if I can make something happen. Still no extensions get loaded.

**Comment by decebals** [comment]
I don't have enough information.
I understand that you have one or more jar files (plugins) in the application's classpath, each jar contains `META-INF/services/<extension-point>` and if you call `pluginManager.getExtensions(<extension-point>)` you retrieved an empty list, correct?
I have a demo that works OK. You help me if you create a minimalist public project that reproduce the issue. If I have some time I will try to create myself this test application.

**Comment by jchappelle** [comment]
Yes. I get an empty list.

Sure. I will work on creating a quick start. Actually it will be a wicket project, api and a plugin project. 3 separate projects(not one maven multi-module). I'll get that to you ASAP.

I'll mention one additional thing. I noticed in the Boot class in pf4j-demo-app the following gets logged and I never see a similar log message in my app.

`2016-02-22 11:26:38,700 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Loading class 'ro.fortsoft.pf4j.demo.HowdyGreeting' using class loader 'sun.misc.Launcher$AppClassLoader@4e0e2f2a'`

**Comment by decebals** [comment]
Please see https://github.com/decebals/pf4j-test, a very simple test.
The test application run OK, see bellow the console log:
```
2016-02-22 20:57:51,502 INFO ro.fortsoft.pf4j.DefaultPluginManager - PF4J version 0.12.0 in 'development' mode
2016-02-22 20:57:51,512 INFO ro.fortsoft.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
2016-02-22 20:57:51,512 INFO ro.fortsoft.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2016-02-22 20:57:51,514 DEBUG ro.fortsoft.pf4j.DefaultPluginManager - Lookup plugins in 'C:\Users\decebal\work\plugins'
2016-02-22 20:57:51,514 ERROR ro.fortsoft.pf4j.DefaultPluginManager - No 'C:\Users\decebal\work\plugins' directory
2016-02-22 20:57:51,516 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Finding extensions for extension point 'com.myproject.Animal'
2016-02-22 20:57:51,516 DEBUG ro.fortsoft.pf4j.ServiceProviderExtensionFinder - Reading extensions storages from classpath
2016-02-22 20:57:51,520 DEBUG ro.fortsoft.pf4j.ServiceProviderExtensionFinder - Read 'C:\Users\decebal\work\pf4j-test\target\classes\META-INF\services\com.myproject.Animal'
2016-02-22 20:57:51,526 DEBUG ro.fortsoft.pf4j.ServiceProviderExtensionFinder - Found possible 2 extensions:
2016-02-22 20:57:51,526 DEBUG ro.fortsoft.pf4j.ServiceProviderExtensionFinder -    com.myproject.Dog
2016-02-22 20:57:51,526 DEBUG ro.fortsoft.pf4j.ServiceProviderExtensionFinder -    com.myproject.Cat
2016-02-22 20:57:51,527 DEBUG ro.fortsoft.pf4j.ServiceProviderExtensionFinder - Reading extensions storages from plugins
2016-02-22 20:57:51,527 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Loading class 'com.myproject.Dog' using class loader 'sun.misc.Launcher$AppClassLoader@71e2b67c'
2016-02-22 20:57:51,529 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Checking extension type 'com.myproject.Dog'
2016-02-22 20:57:51,531 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Added extension 'com.myproject.Dog' with ordinal 0
2016-02-22 20:57:51,531 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Loading class 'com.myproject.Cat' using class loader 'sun.misc.Launcher$AppClassLoader@71e2b67c'
2016-02-22 20:57:51,533 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Checking extension type 'com.myproject.Cat'
2016-02-22 20:57:51,533 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Added extension 'com.myproject.Cat' with ordinal 0
2016-02-22 20:57:51,533 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Found 2 extensions for extension point 'com.myproject.Animal'
2016-02-22 20:57:51,533 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Finding extensions for extension point 'com.myproject.Animal'
2016-02-22 20:57:51,534 DEBUG ro.fortsoft.pf4j.LegacyExtensionFinder - Reading extensions storages from classpath
2016-02-22 20:57:51,534 DEBUG ro.fortsoft.pf4j.LegacyExtensionFinder - No extensions found
2016-02-22 20:57:51,534 DEBUG ro.fortsoft.pf4j.LegacyExtensionFinder - Reading extensions storages from plugins
2016-02-22 20:57:51,534 DEBUG ro.fortsoft.pf4j.AbstractExtensionFinder - Found 0 extensions for extension point 'com.myproject.Animal'
2016-02-22 20:57:51,534 DEBUG ro.fortsoft.pf4j.DefaultExtensionFactory - Create instance for extension 'com.myproject.Dog'
2016-02-22 20:57:51,534 DEBUG ro.fortsoft.pf4j.DefaultExtensionFactory - Create instance for extension 'com.myproject.Cat'
animals.size() = 2
animal.getName() = Dog
animal.getName() = Cat
```

**Comment by jchappelle** [comment]
In my quick start it is working as you describe. That means it's a problem on my end. I'll get it figured out.

Sorry for the trouble.

**Comment by jchappelle** [comment]
I've found the issue. 

It appears the ServiceLoader will search all jar files for the META-INF/services folder but the PF4J library only parses the first META-INF/services folder that is found.

I proved this in my quick start by adding a second plugin. For the ServiceLoader implementation I can see both my plugins, however with the PF4J I only see the first one. In fact, if I reorder my runtime dependencies on the plugins, I can see only the second plugin and not the first. However with the ServiceLoader, I see them both appearing in reverse order.

The reason this was a problem for me in my real app was that the wicket-plugin has a META-INF/services folder and plus there are other frameworks that I'm using that do(like spring-batch). 

I will post my 4 projects that prove this functionality.

**Comment by jchappelle** [comment]
[pf4j-wicket-quickstart-all.zip](https://github.com/decebals/pf4j/files/141235/pf4j-wicket-quickstart-all.zip)

Here is the zip file with all 4 projects in it. I have also included 2 screenshots, one for the resulting page with PF4J and one using ServiceLoader.

Notice the dependencies in the pf4j-wicket-quickstart pom file for the plugins. To change between ServiceLoader or PF4J go to the WicketApplication.getExtensionProvider method and change the implementation being returned.

Thanks for any help on this. I think this would be a real hurdle for others so getting this fixed would definitely improve the library.

**Comment by decebals** [comment]
Please use the last code from github (0.13.0-SNAPSHOT) to confirm me that this issue persists.

> The reason this was a problem for me in my real app was that the wicket-plugin has a META-INF/services folder and plus there are other frameworks that I'm using that do(like spring-batch).

If I understand you, I have the same dilemma but I don't care to much that are many `META-INF/services` in my application classpath that contain Services that are not (PF4J) Extensions. The interoperability with ServiceLoader is a feature to make easy the adoption of PF4J in application that are modular via ServiceLoader. If I want to be more strict I will use `@Extension` instead of SerciceLoader.

**Comment by jchappelle** [comment]
With the 0.13.0-SNAPSHOT I don't see any plugin messages.

**Comment by decebals** [comment]
Thanks. I will take a look.

**Comment by jchappelle** [comment]
I finally got my app working with PF4J using @Extension. Maybe I shouldn't have assumed EXACT interoperability with ServiceLoader. I understand if you feel like it is not something that is within the scope of the project, but you might want to list that as a limitation under your "ServiceLoader interoperability" section. Any app worth slowly migrating to another framework is likely to have several jar files, any of which may have the WEB-INF/services folders in their classpath.

For the annotation processing I added a configuration to my maven build. It's a few steps to make eclipse do this for you and I didn't want to have to educate other developers on how to do it so adding to the maven build is a clean solution. The maven-compiler-plugin can be configured to do this like so:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>2.5.1</version>
	<configuration>
		<annotationProcessors>
			<annotationProcessor>ro.fortsoft.pf4j.processor.ExtensionAnnotationProcessor</annotationProcessor>
		</annotationProcessors>
	</configuration>
</plugin>

```
You might consider adding that to the README documentation.

Thanks for your help with everything thus far!

**Comment by decebals** [comment]
> I finally got my app working with PF4J using @Extension. Maybe I shouldn't have assumed EXACT interoperability with ServiceLoader. I understand if you feel like it is not something that is within the scope of the project, but you might want to list that as a limitation under your "ServiceLoader interoperability" section. Any app worth slowly migrating to another framework is likely to have several jar files, any of which may have the WEB-INF/services folders in their classpath.

It's a bug in PF4J (it don't see all `META-INF/services` from the classpath). I will try to fix it in the next release.

> The maven-compiler-plugin can be configured to do this like so:

I don't think that you need this. PF4J has a special file called `javax.annotation.processing.Processor` located in `META-INF/services` in the .jar file. In the demo application I don't have the `configuration` entry for `maven-compiler-plugin` and everything is OK from command line. Right now I work with IDEA and I cannot give you an advice for eclipse.

**Comment by jchappelle** [comment]
It was necessary for me. Eclipse doesn't do this by default and I would think our Jenkins build server probably would not either. Besides, something that should happen at compile time needs to be inside the maven pom. It's not good to depend on someone's IDE configuration.

**Comment by decebals** [comment]
> It's not good to depend on someone's IDE configuration.

I don't talk here about IDE. For demo application I do this from command line.

**Comment by jchappelle** [comment]
Which proves even further that it's part of the build process. It belongs
in the plugin's pom.
On Feb 23, 2016 8:52 AM, "Decebal Suiu" <notifications@github.com> wrote:

> It's not good to depend on someone's IDE configuration.
>
> I don't talk here about IDE. For demo application I do this from command
> line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/decebals/pf4j/issues/92#issuecomment-187727680>.
>

-- 



NOTICE: This electronic mail message and any files transmitted with it are 
intended exclusively for the individual or entity to which it is addressed. 
The message, together with any attachment, may contain confidential and/or 
privileged information. Any unauthorized review, use, printing, saving, 
copying, disclosure or distribution is strictly prohibited. If you have 
received this message in error, please immediately advise the sender by 
reply email and delete all copies.

**Comment by decebals** [comment]
Sure but I don't have the `configuration` entry for `maven-compiler-plugin` in the `pom.xml`

**Comment by jchappelle** [comment]
As a user of your library I'm telling you that simply documenting this maven-compiler-plugin as an option to building the extensions.idx file will be very helpful to others. That's all I'll say about it.

**Comment by decebals** [comment]
OK. I will add your observation in the user guide. If you have some time I will be happy to receive PRs that improve the documentation. Thanks.

**Comment by jchappelle** [comment]
Thanks. Sure I'd be happy to.

**Comment by decebals** [comment]
> As a user of your library I'm telling you that simply documenting this maven-compiler-plugin as an option to building the extensions.idx file will be very helpful to others. That's all I'll say about it.

Done

**Comment by janhoy** [comment]
Can this be closed?

**Comment by jchappelle** [comment]
Yes
