### ISSUE TITLE
WARN  ro.fortsoft.pf4j.AbstractExtensionFinder

### ISSUE THREAD

**Issue by tarkal** [decebals/pf4j#98]
After the last update my logs are showing a warning:

```
2016-03-31 [qtp1609509548-82] WARN  ro.fortsoft.pf4j.AbstractExtensionFinder - 'co.ff36.halo.plugin.email.EmailSettings' is not an extension for extension point 'co.ff36.halo.core.plugin.api.services.DispatchServices'
2016-03-31 [qtp1609509548-82] WARN  ro.fortsoft.pf4j.AbstractExtensionFinder - Different class loaders: 'sun.misc.Launcher$AppClassLoader@58644d46' and 'ro.fortsoft.pf4j.PluginClassLoader@2c835477'
```

The seems to happen for plugins that implement multiple extension points. The above warning is generated for a plugin that implements both the `co.ff36.halo.core.plugin.api.services.DispatchServices` and `co.ff36.halo.core.plugin.api.services.SettingServices` extension points.

**Comment by decebals** [comment]
The warn is related to commit https://github.com/decebals/pf4j/commit/a866af82241692825139e57508a93366e0ca85a6 (Try to create a defense for the issues similar with #97). The warn say that `EmailSettings` is not an extension for extension point `DispatchServices` (I suppose that `EmailSetiings  implements DispatchServices` but you are two different class loaders - app class loader and a plugin class loader).
Did you see all expected extensions for that extension point? Is it an issue related to functionality or do you talk that it is an unwanted entry in your log ?

**Comment by tarkal** [comment]
At the moment it seems to just be a logging issue. As far as I can tell everything is executing correctly but I am ending up with 1000's of log entries every time a plugin is invoked. Can this be a debug log instead?

**Comment by decebals** [comment]
I see that in my last commit I changed the log level from `debug` to `warn` and I added a new log entry (with warn level) with information about the class loaders.
So, it's strange that you have so many lines with this warn. In normal mode you call `PluginManager.getExtensions(MyExtensionPoint.class)` only for extension point classes and not for 1000 non extension classes.
I tell you all these because I try to create a real, non intrusive defense for #97 (a common and very ugly situation). 
I can anytime release a new critical version (0.13.1) that fix the current issue but I wish to be sure that my  last commit is a mistake and it doesn't help.

**Comment by tarkal** [comment]
You are correct that the log occurs when `PluginManager.getExtensions(MyExtensionPoint.class)` is invoked. The problem is that in our system plugins are context sensitive. This means that the calling user or entity  loads only the extensions that they have permission to access. Compounded by the fact that for API calls we cannot maintain a memory session. The system currently runs approximately 500 concurrent users and some users will have 20 plugins. Some plugins get called 1 a day some as often as   1 a min. With 2 lines of logging per invocation we end up with 1000 of superfluous log entries.

Debug would be much better in my scenario but I can see that #97 would benefit from it as warn. One possible solution could be to overload `find(Class<T> type)` to accept a log level argument, it could probably just be boolean `find(Class<T> type, boolean warnLog)`.

**Comment by decebals** [comment]
> This means that the calling user or entity loads only the extensions that they have permission to access.

I suppose that you can apply the permission filter (user base) after you retrieve the extensions for an extension point.
The warn is throws only if you call `PluginManager.getExtensions(...)` for non extension points or for extensions that are in trouble (class loader issues) and I don't think that you are in that situation.
I try to understand your scenario because I think it's a particular one.

**Comment by tarkal** [comment]
I think we have crossed wires. Let me try to explain better. If I have a plugin that has more than 1 extension point. So in the host I declare the following extension points to my interfaces:

```
public interface SettingServices extends ExtensionPoint {...}
```
```
public interface DispatchServices extends ExtensionPoint {...}
```

And in the plugin I have the following:

```
@Extension
public class ExampleSettings implements SettingServices {...}
```
```
@Extension
public class ExampleDispatcher implements DispatchServices {...}
```

Now I load and start just that plugin into the plugin manager and when I call `pluginManager.getExtensions(DispatchServices.class);` I get the following log generated:

```
2016-04-01 [qtp1609509548-1084] WARN  ro.fortsoft.pf4j.AbstractExtensionFinder - 'co.ff36.halo.plugin.example.ExampleSettings' is not an extension for extension point 'co.ff36.halo.core.plugin.api.services.DispatchServices'
2016-04-01 [qtp1609509548-1084] WARN  ro.fortsoft.pf4j.AbstractExtensionFinder - Different class loaders: 'sun.misc.Launcher$AppClassLoader@58644d46' and 'ro.fortsoft.pf4j.PluginClassLoader@3a213668'
```

**Comment by decebals** [comment]
This means that it's a bug in PF4J. I will check. Thanks.

**Comment by decebals** [comment]
@tarkal Do you see any problem with f79c200 commit (a check is made with `log.isTraceEnabled()` so you cannot see these messages in the log file without to set the log level to TRACE)?
