### ISSUE TITLE
stopPlugin NPE 

### ISSUE THREAD

**Issue by xiyoufang** [decebals/pf4j#99]
If plugins directory is null, load and start a Plugin,  finally stop plugin ：
`Exception in thread "main" java.lang.NullPointerException
	at ro.fortsoft.pf4j.DefaultPluginManager.stopPlugin(DefaultPluginManager.java:340)
	at ro.fortsoft.pf4j.DefaultPluginManager.stopPlugin(DefaultPluginManager.java:317)`
If plugins directory is not null, not have this Exception.
pluginsDirectory is null , **dependencyResolver can't instanced**

**Comment by decebals** [comment]
I will take a look. Pull Request is welcome.

**Comment by decebals** [comment]
You are right, the value of `dependencyResolver` at line 340 in `DefaultPluginManager.stopPlugin(pluginId)` but I don't understand how it's possible.
If the plugins directory is null or empty if you call `DefaultPluginManager.stopPlugin(pluginId)` the first line sin this method are:
```
if (!plugins.containsKey(pluginId)) {
    throw new IllegalArgumentException(String.format("Unknown pluginId %s", pluginId));
}
```

So, I believe that something is strange in your code.
Can you give me more details about this issue?

**Comment by xiyoufang** [comment]
1. Call loadPlugins(). Because plugins Directory is empty, defaultPluginManager.java 392 line directories.length == 0 is true. dependencyResolver is null .
2. Call loadPlugin(File pluginArchiveFile) and startPlugin(pluginId). plugins is not empty, dependencyResolver is null. 
3. Call stopPlugin(pluginId). plugins.containsKey(pluginId) is true, but dependencyResolver is null, in DefaultPluginManager.java 340 line throw NullPointerException.

**Comment by heyokajan** [comment]
By adding a small check on dependencyResolver not being null or else skipping the line where it trigger the NPE fixed the issue for me. It happens for plugins without dependencies in most projects both with version 0.13 and the snapshot version of 0.14. Basically this confirms the finding xiyoufang mentioned in his/her comment. This bug even occurs by using the sample code only in the sample projects. I am not sure if you have this fixed yet. If it has been fixed ignore this post all together.

**Comment by decebals** [comment]
@heyokajan Thanks for comment. I will check if the fix is already pushed on github and if it's not then I will push the fix.

**Comment by decebals** [comment]
@xiyoufang,  @heyokajan Please try the fix and confirm that the issue is resolved.

**Comment by justinnichols** [comment]
Is there a workaround for this until the next release?

**Comment by decebals** [comment]
I don't have any feedback from people if this issue is resolved or not on trunk. I updated the SNAPSHOT version. 
All I want to add for next version is a protection for https://github.com/decebals/pf4j/issues/82 (extension not found) because is very time consuming for me to offer support for this kind of problem.
If this issue is a stopper for you and if the bug is resolved in trunk (please test yourself) I can release a new version that will contain this bug fix.

**Comment by justinnichols** [comment]
I will test based on the SNAPSHOT, thanks!

**Comment by justinnichols** [comment]
Confirmed, 0.14.0-SNAPSHOT fixes this issue for me.

**Comment by justinnichols** [comment]
I can stay on the snapshot for now, but definitely would love to go back to release once you feel 0.14.0 is ready.

**Comment by decebals** [comment]
@justinnichols Thank you for confirmation
